BoostIO/Boostnote

lib/hotkey.js
バックグラウンドから表示するときにはすぐに検索したいので
ホットキーでメイン画面を表示した際に、検索ボックスにフォーカスするようにしました。
> masterだとloading画面で止まってしまうようだったので、
修正済み(?)の開発ブランチ宛にプルリクします…
=> Quick searching

gruntfile.js, package.json
This PR, adds support to create .deb files to simplify Boostnote installation process of Linux based systems.
=> Add support for creating .deb file on linux

browser/styles/main/ArticleList.styl, browser/styles/theme/dark.styl
----
ダークテーマを追加した時にMarkdownプレビュー時の
テーブルのスタイルのオーバーライドが漏れてましたので追加でスタイルを定義しました。
メモ削除時のモーダル表示のボタンスタイルが未定義だったため追加しました。
下記変更にともなって生じた、AceEditor切替時に出る白い余白を修正しました。
https://github.com/BoostIO/Boostnote/commit/934e4d9607f89ccd65d0bf4f3898ae8f2def3535#diff-9facd39aca37bb6f900638a5ae61410aR386
- code タグの背景色を設定
- リストのフォルダ名に文字色を設定し位置調整
=> Hotfix for dark theme

.gitignore, browser/lib/markdown.js, browser/styles/mixins/marked.styl
Code blocks with line numbers.
**NOTE**: I wanted to use CSS classes, but somehow the `class` tags were removed after.
The
```stylus
&>.cl
display block
clear both
```
in `marked.styl` is not really necessary, it seems to work without.
=> displaying markdown codeblocks with line numbering

readme.md
The ordered lists in `readme.md` were not rendered properly (every item was detected as `1.` by the parser).
This is only a formatting issue to make the steps clearer, I have not changed any word or sentence.
=> fix lists formatting in readme.md

.gitmodules, gruntfile.js, lib/finder.html, lib/main.html, package.json
This update will not require ace as submodules anymore.
It just needed this entry in the package.json:
`"ace": "git+ssh://git@github.com/ajaxorg/ace.git"`
=> including ace via npm, not as git submodule anymore

browser/main/modals/PreferencesModal/StorageItem.js, browser/main/modals/PreferencesModal/StoragesTab.js, browser/main/modals/PreferencesModal/index.js, package.json
This PR is based on the feature request in issue #36. I've implemented a color picker dialog instead of a list of predefined colors for the folders. I hope that we did not do work twice, but I just needed that feature for my notes. ;)
The PR makes use of the wonderful [react-color](https://github.com/casesandberg/react-color/) component which is licensed by the [MIT license](https://github.com/casesandberg/react-color/blob/master/LICENSE).
Actually calculating the position is not that easy because the dimensions of the content area of the modal is required. I calculate the dimensions after they are available and hand them as properties to the child components. You might want to have a closer look to the code to see if you're d'accord with this procedure or if this can be done better. Also …
=> Feature: Folder color picker

browser/main/Detail/TagSelect.js
In existing implementation, 'enter' key is only allowed to submit the tag. However, if the user finishes to create the tag and make another tag, the user naturally send 'tab' key.
When receiving 'tab' key, the focus will go to the star icon and nothing is submitted, but the text is still remained. This makes confusing to the user.
This commit provide 'tab' key submitting the tag also.
=> submit the tag when receiving 'tab' key

docs/build.md, docs/jp/build.md, docs/ko/build.md, package.json
Stylus-loader has already been fixed #50 problem. 
They discussed in this [issue](https://github.com/shama/stylus-loader/issues/120) and fixed in this [commit](https://github.com/shama/stylus-loader/commit/9454f49001f04988a15a7a34e88f10d06bef4922)
I have test with node 4.4.4 and latest stable 6.4 and works well with both.
=> Node 6 support

browser/components/CodeEditor.js
In browser/components/CodeEditor.js, export default CadeEditor called twice. No need exporting twice. 
```
node_modules/.bin/webpack --config webpack-production.config.js
Hash: 3c381874bfbab95a1e49
Version: webpack 1.13.2
Time: 24538ms
+ 431 hidden modules
ERROR in ./browser/components/CodeEditor.js
Module build failed: SyntaxError: Only one default export allowed per module.
265 | }
266 | 
> 267 | export default CodeEditor
| ^
268 | 
```
=> multiple export default causes a error

oh-my-cdn.json
```
　　　　　　　　 ,,　＿ 
　　　　　　　／ 　　　 ｀ ､ 
　　　　　　/　　(_ﾉL_）　 ヽ 
　　　　　 /　　 ´・　 ・｀　　l　　　　npmcdn is dead.
　　　　 （l　 　　　し　　　　l）　　　it is renamed to unpkg.
　　　　　l　　　　＿＿　　 l　　　　you should use unpkg instead of npmcdn.
　　　　　 >　､ _ 　　　　 ィ 
　　　　 ／　 　　　￣　　 ヽ 
　　 　 /　|　　　　　　　　　iヽ 
　　　　|＼|　　　　　　　　　|/| 
　　　　|　||/＼／＼／＼/|　| 
```
=> npmcdn is dead

readme.md
Correct misspelling of the crowd-funding platform's name.
=> Pateron => Patreon

browser/main/TopBar/index.js
Instead of a standard `console.log` I've added an alert. Pressing the button and getting nowhere is not good from a user perspective.
=> Improved error messaging

browser/main/modals/PreferencesModal/StorageItem.js
The unlink storage in the preference popup isn't working due to an error of calling dispatcher method. With this fix, it should working again.
=> Fix of storage unlink in preference popup

browser/main/modals/PreferencesModal/ConfigTab.styl, lib/main-menu.js
This updates the accelerator to use the OSX boolean instead of a new function where appropriate.  Also, for accelerators that are identical across platforms *except* for Command/Control, the 'CmdOrCtrl' modifier is used.
Edit:
The dark theme will also be applied to the input boxes and dropdowns in the Config modal.
=> Minor accelerator updates

oh-my-cdn.json
[This](https://cdn.rawgit.com/bramp/js-sequence-diagrams/master/build/sequence-diagram-min.js) previous url returns 404. So I fixed to proper url.
=> URL is no longer available

browser/components/MarkdownPreview.js, browser/main/lib/ConfigManager.js
Hello, I get an error on loading css in preview code block like this picture below.
```
file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/codemirror/theme/default.css Failed to load resource: net::ERR_FILE_NOT_FOUND
```
It means default.css is not available. Thus I tried to fix it. Then I found the default theme `xcode` is no longer available too. Perhaps the theme `elegant` is the most similar to previous one (I attach Screen Shot below).
Please point out if I am wrong.
=> Fixes the theme of code block by codemirror

package.json
Hello, I got an error on `npm i`
```
[ Boostnote 11:17 ]% npm i                                                     [master]
> boost@0.8.0 postinstall /Users/ryouta/Boostnote_repo/Boostnote
> npm run vendor
> boost@0.8.0 vendor /Users/ryouta/Boostnote_repo/Boostnote
> oh-my-cdn
oh-my-cdn.json doesn't exist.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "vendor"
npm ERR! node v4.4.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! boost@0.8.0 vendor: `oh-my-cdn`
npm ERR! Exit status 1
```
According to https://github.com/BoostIO/Boostnote/commit/76508fbc3b0fca931257376c0af44a26c7db614d, oh-my-cdn is removed.
refs: https://github.com/BoostIO/Boostnote/issues/140
=> Fixes npm task bacause oh-my-cdn is removed

browser/components/StorageItem.styl
Hi, I fixed https://github.com/BoostIO/Boostnote/pull/224
=> refs #224 Fixes the style of folder-list

lib/main-window.js
For now, I'd like to suggest ignoring any errors at `config.set('windowsize', mainWindow.getBounds())`. I checked this code behaviors as expected.
https://github.com/BoostIO/Boostnote/issues/243
=> Fix a bug due to event handler of before-quit on update

browser/main/StatusBar/index.js
The current max zoom % (130%) is a bit small on large screen (3840 x 2160, hi-resolution but not so large display etc.).
Probably, it is also related to the default text color (`#939395`) or the font-weight (`normal`) but more zoom % makes text more readable enough.
e.g. 130% (current max zoom, a bit small), 150% (readable), 200% (super readable, a bit large)
See also: https://github.com/BoostIO/Boostnote/issues/31#issuecomment-267843725
=> modify: add more zoom options (140-200%)

browser/finder/FinderMain.styl
Unify finder background color result-list
=> unify finder backgroundcolor

browser/components/MarkdownPreview.js, browser/main/NoteList/index.js, lib/main-menu.js
Hi, I implemented a function which exports as txt or md. I heard it was said that someone wants this function.
=> Add export as txt/md

browser/components/MarkdownEditor.js, browser/main/TopBar/index.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/HotkeyTab.js, lib/main-menu.js
Hi, I added a shortcut to focus the note as `Ctrl + E`. Please feedback what you feel this shortcut.
=> Adds shortcuts

browser/components/MarkdownPreview.js
Hi, I fixed the bug reported by https://github.com/BoostIO/Boostnote/issues/208.
I referenced GitHub for this style.
=> Fixes syntax hilight of inline code on Preview

browser/components/CodeEditor.js
Hi, I enabled to drop images into CodeEditor like this:
Next, to handle broken link, I should implement saving images into a directory for boostnote.
=> Dropping images into CodeEditor

browser/components/MarkdownEditor.js
Hi, I fixed a reported bug which is escaped on pressed any key in CodeEditor when you focus for editing the note by click.
related: https://github.com/BoostIO/Boostnote/issues/268
=> Fix Ctrl + E shortcut on escape from CodeEditor

browser/components/MarkdownPreview.js
Hello, I find a bug in code area on writing HTML entity. They would not be decoded.
And I added encode, it works fine like below.
=> Decodes HTML entity in code area

browser/components/CodeEditor.js
This should fix dragging image into text editor, which wasn't working, and thanks to escaping it now works with files with spaces in name.
=> Image drag fix

browser/components/MarkdownEditor.js, browser/main/Detail/MarkdownNoteDetail.js
Hi, I added a function which keeps Editor mode even though I move to another window.
refs: https://github.com/BoostIO/Boostnote/issues/272
=> Enable lock in MarkdownEditor

browser/components/CodeEditor.js, browser/components/MarkdownPreview.js
Disable dragging an image to MarkdownPreview
And I fixed the behavior of an image dropped to CodeEditor. Please pay attention to the position of the cursor. Even I drop an image to the bottom of CodeEditor, it is pasted at the position of the cursor.
=> Disable dragging an image to MarkdownPreview and fix the behavior of an image dropped on CodeEditor.

browser/components/markdown.styl, browser/lib/markdown.js, package.json
This pull request contains a feature, that allows the use of a table of contents inside the markdown by typing `@[TOC]`. That uses the `markdown-it-toc-and-anchor` project from the nodejs repository.
This allows a simple ToC creation, where a click onto it, automatically moves the view to the selected item.
This also fixes two bugs.
- background color of the `taskListItem` is now transparent instead of white in the light theme (looks a lot better now)
- a bug is fixed, that would select the whole text, every time one tries to select or switches between editor and preview the whole preview text would be selected. This made the selection of small text parts impossible
Thanks
=> Added Table of Contents and two small bug fixes

browser/main/Detail/SnippetNoteDetail.js
Previously, it was not deleted even if you pressed the delete button.
Now it is deleted by pressing the delete button.
=> The snippet subtab was successfully deleted.

browser/main/Detail/MarkdownNoteDetail.js
I solved the [issue](https://github.com/BoostIO/Boostnote/issues/323#issuecomment-287097442).
Previously, a character string beginning with '#' in the code block was treated as the title of the markdown note.
Currently, strings beginning with '#' in the code block are ignored.
=> ignore # in the code block

browser/components/CodeEditor.js
I solved #329 
When I drag svg file to markdown editor, its path and its xml data is entered in editor. Also its path is not display its image data.
When I drag svg file markdown editor, its path is entered in editor. Its xml data is not entered in editor. Also, its image data is displayed in preview.
Also, This pull request can solve the bug which is to display image data in full screen which is dragged to markdown preview.
=> dragged svg file is turns not into xml text

browser/components/MarkdownPreview.js, browser/components/markdown.styl
* fix the design of li (deletion of '・' in front of the checkbox content)
* fix the design of markdown-it-TOC
=> Fix the design of li

browser/components/MarkdownEditor.js
I added a shortcut for inputting `****` and it brings the caret to the center of `****`.
=> Add a shortcut for supporting to input bold

browser/components/MarkdownEditor.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/MarkdownNoteDetail.styl, browser/main/Detail/NoteDetailInfo.styl, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/SnippetNoteDetail.styl, browser/styles/index.styl
A feature what lock the editor behaves incorrectly.
Sometimes, even the lock is opened, the editor keeps its mode when I move another item. Thus I fixed it.
=> Fix the behavior of a feature which locks the editor

browser/components/CodeEditor.js, browser/main/Detail/SnippetNoteDetail.js
This should fix the issue for you.
=> fix: #288 Fixed Snippet tabs overwriting other tabs when closed

package.json
Hi. There is a request to run npm tasks parallel. So I added `concurrently` and `npm run dev-start` task.
=> Add concurrently for running local environment more easily

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js
Hi. I don't wanna see a menu which contains only `delete`.
=> Remove a menu which is shown on clicked the trash button

lib/main-window.js
I fixed it. But I don't have any ways to check the behavior of windows or Linux. Someone, please help me.
https://github.com/BoostIO/Boostnote/issues/332#issuecomment-288311835
=> Fix the screen become black on closing Boostnote when a state of Boostnote is fullscreen on mac

browser/components/CodeEditor.js
Hello. I changed the code to use `newlineAndIndentContinueMarkdownList` which is defined in `node_module/codemirror/addon/edit/continuelist.js`of library named`codemirror`. It'll fix the new line issues in list and task list. 
This will cover these issues in [List of the requested features](https://github.com/BoostIO/Boostnote/wiki/List-of-the-requested-features#markdown-note)
=> Fix new line problem in list and task list

browser/components/SnippetTab.js
Double click is more convenient i guess. When opening a new snippet, the first thing i have to do is rename the first tab, thus rename is always the thing need to be done first and with the current flow, i have to right click, select rename, which is slow
=> double click on tab to rename

browser/components/MarkdownEditor.js
to improve upon #301
ctrl + : to bold a single word under caret or bold selected text if some text is selected (highlighted)
#463
=> Add support to bold selected text via kb shortcut

lib/main-menu.js
=> Fix text on menu bar(macOS) and some refactor

browser/main/Detail/index.js
Sadly, I forgot to rename this function name in https://github.com/BoostIO/Boostnote/pull/340 :fearful: Due to this, a bug happens and we cannot use a shortcut for deletion a note. Sorry for inconvenient.
```
Uncaught TypeError: o.refs.root.handleDeleteMenuClick is not a function
```
* macOS
* Boostnote v0.8.8
=> Fix a shortcut for deletion

browser/components/StorageItem.styl, browser/main/SideNav/StorageItem.styl
=> Improvement of sidebar uiux

browser/components/NoteItem.styl
=> fix: modify the star layout at NoteItem

browser/components/MarkdownPreview.js, browser/lib/htmlTextHelper.js, tests/lib/html-text-helper-test.js
Finally, I fixed this problem which is reported by https://github.com/BoostIO/Boostnote/issues/333 and https://github.com/BoostIO/Boostnote/issues/294.
Before, this code didn't work well in CodeBlock: `<port protcol="tcp" port="10022"/>`
=> Fix incorrect tag completion in code block

browser/main/lib/modal.js
Edit NoteList style properties on modal component. 
Remove overflow to hide scrollbar on modal open.  (#504 )
=> fixes (#504) scrollbar no longer appears above modal.

.travis.yml
I fixed this issue: Spectron doesn't run even master branch because there's no `$` before variables.
=> Fix viriables for travis

browser/components/MarkdownEditor.js
- use keyCodes instead of strings to detect keys
- delete key from keyPressed array on key up
- fix #540
=> Revamp handling of multiple key press

browser/components/TodoListPercentage.styl, browser/components/TodolistPercentage.js, browser/main/Detail/MarkdownNoteDetail.js
I heard that There are people who using Boostnote as todo list. So, I made percentage of achievement it visible.
=> display percentage of achievement of todo in markdown

browser/main/Detail/MarkdownNoteDetail.js
This PR can resolve the [issue #495](https://github.com/BoostIO/Boostnote/issues/495).
Before
***
After
***
=> fix the bug when using markdown syntax h1

browser/components/NoteItem.js, browser/components/NoteItemSimple.js, browser/components/StorageItem.js, browser/main/NoteList/index.js, browser/main/SideNav/StorageItem.js
I made it allows move note between folders by drag and drop.
=> Move note between folders

browser/components/TodoListPercentage.styl
=> Fix task bar UI

browser/components/NoteItem.styl
=> If there is no tag, narrow the width of NoteList.

.travis.yml
Fix the version of travis to 4.x to deal with a problem what e2e tests timeout due to updates.
And I confirmed the e2e tests passes.
https://travis-ci.org/asmsuechan/Boostnote/jobs/239005788
=> Fix travis node version

browser/components/MarkdownEditor.js, browser/components/MarkdownEditor.styl
Fix for #535:
- hide/show code editor based on markdown editor state (could be CODE or PREVIEW);
- changed styles for code editor;
I did changes the same way as there were for markdown preview component.
=> Fix for #535:

browser/lib/search.js, browser/main/NoteList/index.js, browser/main/TopBar/index.js, browser/main/index.js
Display the searched note in a popup window.
Display the searched notes in the normal note list.
=> change search ux

browser/components/CodeEditor.js, browser/components/MarkdownEditor.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/lib/dataApi/copyImage.js
This PR enable that to copy an image when it is dropped into CodeEditor. It means the image is kept into boostnote storage: `~/Boostnote/images/imageName.png`
=> Add dataApi.copyImage for copying image to boostnote storage on an image dropped into CodeEditor

browser/lib/findNoteTitle.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, tests/lib/find-title-test.js
I added a module to find a title of a note.
=> Add a module to find the title

browser/main/NoteList/index.js
=> Fix a bug which is not showing dialog when user tries to export a snippet

browser/main/NoteList/index.js
Previously I changed search UX. I think it is better than previous ones. However, when searchTextBox is empty, NoteList become empty too. So, I improved search UX again.  As a result, when searchTextBox is empty, NoteList display AllNotes.
=> improve searchTextBox UX

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/MarkdownNoteDetail.styl, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/SnippetNoteDetail.styl, browser/main/Main.js, browser/main/Main.styl
I handled with https://github.com/BoostIO/Boostnote/pull/602.
=> Handling pull 602

browser/components/MarkdownPreview.js
Show a notification when a copy button, which is in a codeblock, is clicked.
=> Add notification on a copy button clicked

browser/main/lib/dataApi/init.js, browser/main/lib/dataApi/resolveStorageNotes.js, browser/main/store.js
This PR is for replacing `season` instead of `Rokt33r/season`. When I tried to replace it (refs: https://github.com/asmsuechan/Boostnote/pull/5), one of my note could not be parsed and Boostnote cannot display any notes.
=> Fix errorhandling on cases of invalid notes

browser/main/NoteList/index.js, lib/main-menu.js
Hi there. I implemented a function which imports files from .md or .txt.
* multiple files
* .md or .txt
If someone wants what else, please comment.
* fill a title after imported immediately
I'll implement `fill a title` after https://github.com/BoostIO/Boostnote/pull/324 is merged.
* enable to import files from a directory
=> Add importer which imports files from .md/.txt

browser/components/CodeEditor.js
I added copy feature into the existing shortcut (C-c). It doesn't prevent the ordinal feature.
ref: https://github.com/BoostIO/Boostnote/issues/646
=> Make Ctrl-C copy

package.json
Spectron is a devDependency so I moved the package there where it belongs. This helps when building from source to reducere the size of the Boostnote package since we do not need Spectron in a production environment.
=> Fix dependency type of Spectron module

browser/main/Main.js, browser/main/Main.styl
I already check this PR works good in Windows .
=> Fix not to show scroll bar when full screen mode in Windows

browser/components/CodeEditor.js, browser/main/lib/dataApi/copyImage.js
I changed an image name to a random string to avoid duplication when it's dropped. And remove `encodeURI()`.
```
```
`%20` changes to ` ` and `filename` changes to `skgvvqw0ozbprpb9`.
ref: https://github.com/BoostIO/Boostnote/issues/652
=> Randomize the image name when it's dropped

browser/components/NoteItem.js, browser/components/NoteItemSimple.js, browser/finder/NoteList.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/index.js, browser/main/NoteList/index.js
I remove the menu because it seems useless.
=> Remove the context menu for deletion

browser/main/lib/ConfigManager.js, browser/main/modals/InitModal.js
=> Edit initial files

browser/components/NoteItem.styl, browser/components/NoteItemSimple.styl, browser/main/Detail/FolderSelect.styl, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/NoteDetailInfo.styl, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/TagSelect.styl, browser/main/NoteList/NoteList.styl, browser/main/NoteList/index.js, browser/main/TopBar/TopBar.styl, browser/main/TopBar/index.js
=> Fix layout

browser/lib/date-formatter.js, browser/main/Detail/InfoButton.js, browser/main/Detail/InfoButton.styl, browser/main/Detail/InfoPanel.js, browser/main/Detail/InfoPanel.styl, browser/main/Detail/LastUpdatedString.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/index.js, tests/date-formatter-test.js
I implemented `InfoPanel` to display the data of a note including `note-hash`.
=> Add info button

browser/components/CodeEditor.js, lib/main.html, package.json, yarn.lock
I want to replace `cm-searchbox` to the official search addon because it's very hard to customize.
* Easy to maintain
* Easy to customize
* Officially supported
* Unintuitive behavior
And vim-search is available (Look at the bottom of CodeEditor).
=> Replace cm searchbox to official search addon

browser/components/MarkdownPreview.js
I changed the interface of note-links (it's not released, so the change affects almost nothing).
`[this_is_a_note](#dca2bd793a0bbff3e9a4-8384df059a2659082989)`
`[this_is_a_note](dca2bd793a0bbff3e9a4-8384df059a2659082989)`
=> Remove sharp from note hash on list:jump

browser/components/NoteItem.js, browser/components/SideNavFilter.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/NoteDetailInfo.styl, browser/main/Detail/SnippetNoteDetail.js, browser/main/NoteList/index.js, browser/main/SideNav/index.js, browser/main/TopBar/index.js, browser/main/index.js, browser/main/lib/dataApi/createNote.js, browser/main/lib/dataApi/updateNote.js, browser/main/store.js
I added trash can as well as the star.
TODO:
=> Add trash can

lib/main-menu.js
The reason why `Ctrl-U` is set as a shortcut is that because it conflicts with one of vim-keymaps. Regardless of the escapement, it doesn't work in vim mode. So I change it to `Ctrl-K` because it's more instinctively than the current one. Sadly, even though this PR will be merged, the shortcut for moving an upper note doesn't work on any kind of editor mode.
=> Change the keymap of Ctrl-U to Ctrl-K

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js
As I thought that the dialog box, which appeared when I managed to trash a note, was useless, I removed it.
=> Remove a dialogbox from onTrashButtonClick

browser/main/Detail/InfoPanel.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js
I changed the style of `Note Link` in InfoPanel.
=> Change noteHash to noteLink in the input in InfoPanel

browser/main/lib/dataApi/copyImage.js
It **didn't** create a new directory for a dropped image.
It creates a new directory for a dropped image.
=> Change to create a new directory when storage/images does not exist

browser/main/lib/AwsMobileAnalyticsConfig.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/InfoTab.js, browser/main/modals/PreferencesModal/InfoTab.styl, browser/main/modals/PreferencesModal/index.js
ref: https://github.com/BoostIO/Boostnote/pull/620
=> Add checkbox for ama

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js
Look at `Note Link` in InfoPanel.
`[title](e9604016f1436fd3a3b4-7da4167bc39895940ddf)`
`[Hamlet](e9604016f1436fd3a3b4-7da4167bc39895940ddf)`
If the note is empty, it displays `[](note-hash)`.
=> Change ["title"](note-hash) to [the exact title](note-hash)

browser/main/index.js
An error as follows happens when I clicked `cancel` button on `delete dialog box`.
```
Uncaught TypeError: e.target.className.includes is not a function
```
Although it causes a bug, the application works fine.
The application works fine without the error.
=> Fix a bug on click

browser/finder/index.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/TagSelect.js, browser/main/lib/AwsMobileAnalyticsConfig.js, browser/main/modals/CreateFolderModal.js, browser/main/modals/NewNoteModal.js, browser/main/modals/PreferencesModal/InfoTab.js
Change a method name `recordDynamitCustomEvent` to `recordDynamicCustomEvent`.
=> Fix typos Dynamit to Dynamic

browser/main/Detail/InfoPanel.js, browser/main/Detail/InfoPanel.styl, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js
Left: Export as .md
Right: Export as .txt
=> Add exports to infoPanel

browser/components/CodeEditor.js
The image link was inserted at the bottom of the note when you dropped an image on `CodeEditor`. So I changed it because it's not obviously intuitive.
It was inserted at the bottom of the note.
It is inserted the position of your carret.
https://github.com/BoostIO/Boostnote/pull/293
=> Fix inseration position

browser/main/NoteList/index.js, lib/main-menu.js
Remove Ctrl-G because it's unnecessary and conflicts with one of CodeMirror's search functions.
=> Goodbye Ctrl-G

browser/main/modals/PreferencesModal/InfoTab.js
There's a typo in https://github.com/BoostIO/Boostnote/pull/722.
The part of a sentence was `We collect only the number of DAU for Boostnote and DO NOT COLLECTED any detail information`.
`We collect only the number of DAU for Boostnote and DO NOT collect any detail information`
=> Fix typo in InfoTab

browser/main/Detail/NoteDetailInfo.styl, browser/styles/index.styl
=> Fix hidden button

browser/lib/markdown.js
The path of dropped images was broken on account of `markdownit.render()`. It encodes `\` as `%5C` so it does not work fine in windows.
There's an unexpected decode such as `C:%5CUsers%5Ckazup%5CBoostnote%5Cimages%5C2zyil22t058nnrk9.png`
it does not encode `src` of `img`.
=> iss #727 fix incorrect encoding in link

browser/main/lib/ConfigManager.js
The apostrophe seems something wrong on account of the default font. It is not included in windows by default.
The apostrophe has extra space.
The default font on windows is changed to `Segoe UI` (it's a default font of windows 10).
You have to set `Segou UI` as your font by hand if you custom your UI.
https://github.com/BoostIO/Boostnote/issues/725
=> iss #155 Change defaut font on windows_

browser/components/CodeEditor.js, browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js, browser/finder/NoteDetail.js, browser/main/lib/dataApi/copyImage.js
I made the path of a dropped image relative.
The path of a dropped images was an absolute path such as `/Users/asmsuechan/Boostnote/images/aaaaaaaaaaaa.png`.
`/:storage/aaaaaaaaaaaaaa.png` works now.
=> Make image path relative

browser/components/MarkdownPreview.js
An image path doesn't work on windows.
`file:///C:/Users/kazup/src/Boostnote/libC:\Users\kazup\Boostnote\images/zfod0c0fcw1rwwmi.png`
=> Make it work on windows

browser/main/modals/PreferencesModal/InfoTab.js
Application tried to send the events after ama turned off thus I could not see them properly.
I could not see the event (`DISABLE_AMA`) in aws console.
I'll see it.
=> Change order for AMA event

browser/components/MarkdownEditor.js
`Ctrl-w` did not work in `RIGHTCLICK`.
`Ctrl-w` did not work in `RIGHTCLICK`.
It works.
=> Change to work ctrl-e and ctrl-w in RIGHTCLICK

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js
It's difficult to know where the origin folder of a note is.
No InfoButton
https://github.com/BoostIO/Boostnote/issues/758
=> iss #758 Add InfoButton and InfoPanel in Trash

browser/main/SideNav/StorageItem.js
This is an improvement of `Trash`.
A note counter didn't decrement when the note was trashed.
It works.
https://github.com/BoostIO/Boostnote/issues/757
I assume this logic is not a better way.
=> Fix noteCount on a note trased

browser/lib/search.js, browser/main/NoteList/index.js, tests/lib/search-test.js
It's not intuitive to search from all notes.
Search from all notes.
Search from a specific folder.
https://github.com/BoostIO/Boostnote/issues/747
=> Context search

browser/finder/FinderMain.styl
Fixes the positioning of the My Storage section for the Finder, so that it is no longer shown over the top of the Trash.
Fixes: #761 
Before Fix:
After Fix:
=> Finder UI Fix (My Storage positioning)

lib/main.html
Lato is the default "Preview font family" font. However, in the case that Lato is not installed on the user's system, it falls back to using a different font instead of using the font included with the application.
This means in some cases, such as for the Snippet Note description the wrong font is displayed. Defining Lato as a font-face in main.html fixes this issue.
Before Fix:
After Fix:
=> Add Lato font-face definition to main.html

browser/finder/NoteDetail.js, browser/main/Detail/SnippetNoteDetail.js
If there's any snippet of which type is `Markdown`, the notes fail to load.
`Uncaught Error: Target storage doesn't exist.` happened.
I'm still not sure this will fix https://github.com/BoostIO/Boostnote/issues/742.
=> Add storageKey to MarkdownEditor

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/index.js, browser/main/NoteList/index.js, browser/main/modals/PreferencesModal/StorageItem.js, browser/main/modals/PreferencesModal/UiTab.js
Updates application text in various places to correct the wording, or better reflect the functionality provided.
No notes - From:
No notes - To:
Filter - From:
Filter - To:
Note Deletion - From:
Note Deletion - To:
Unlink Storage - From:
Unlink Storage - To:
UI Preferences - From:
UI Preferences - To:
=> Update application wording

.boostnoterc.sample, browser/main/Main.js, browser/main/lib/ConfigManager.js, browser/main/lib/RcParser.js
I want to manage the configurations of Boostnote in a file.
```
{
"editor": {
"keyMap": "vim",
"theme": "monokai"
},
"hotkey": {
"toggleMain": "Control + L"
},
"listWidth": 174,
"navWidth": 130
}
```
I can put my settings in `~/.boostnoterc`.
It **overwrite** your settings.
=> Add boostnoterc revival

browser/components/NoteItem.js, browser/components/NoteItem.styl, browser/components/NoteItemSimple.styl, browser/components/TodoProcess.js, browser/components/TodoProcess.styl, browser/lib/getTodoState.js, browser/lib/getTodoStatus.js, browser/main/Detail/MarkdownNoteDetail.js
#750 
And I implement it like github todo list.
Before:
After:
Color as same as TodoListPercentage.
Todo style is like github todo style. And todo list doesn't show in folded mode.
Added:
* browser/lib/getTodoState.js get percentage of complete todo helper function
* browser/compoents/TodoProcess.{js/styl}
=> add todo percentage in item list

.boostnoterc.sample, browser/main/lib/ConfigManager.js
It's a bug happens on v0.8.13.
The settings of Boostnote was reset and used DEFAULT_CONFIG unless `~/.boostnoterc` was not created and set settings.
Boostnote reads settings from localStorage and overwrites the settings when `~/.boostnoterc` exists.
=> Fix configmanager

browser/main/lib/RcParser.js
The settings turned DEFAULT if `~/.boostntoerc` is invalid json.
The original settings in localStorage will be used even if `~/.boostnoterc` is invalid json.
=> Make RcParser ignore errors at JSON.parse()

browser/components/NoteItem.js, browser/components/NoteItem.styl, browser/components/TodoProcess.js, browser/components/TodoProcess.styl
=> Fix progress bar ui at Noteitem

.eslintrc, package.json, yarn.lock
Add [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react)
No eslint-plugin-react
It can catch stupid mistakes
=> Add eslint plugin react

browser/main/NewNoteButton/index.js
A bug contains in https://github.com/BoostIO/Boostnote/pull/800.
Cannot open the modal for note creation.
* Open the note-creation modal in `All Notes`
https://github.com/BoostIO/Boostnote/pull/800
=> Fix note creation in All Notes

browser/main/Main.js
The fullscreen button cannot show left columns once they're hidden.
It works fine. I clicked the infobutton but it was a mistake.
https://github.com/BoostIO/Boostnote/pull/802
=> Fix typo regarding fullscreen

browser/lib/markdown.js, package.json
Related to the issue #778 I posed.
I've written a markdown-it plugin for that, and here below is the demo:
=> Support for extended table markdown syntax

lib/main-window.js, package.json
Follow-up on [pull request 534](https://github.com/BoostIO/Boostnote/pull/543)
Sorry for the delay.
=> Fix app name and icon on linux

browser/lib/markdown.js, package.json, yarn.lock
I added markdown-it-named-headers for jumping by a header.
USAGE:
```
[Hello](#Hello)
[Hello World](#Hello-World)
print('hello')
[TOP](#TOP)
print('hello world')
[TOP](#TOP)
```
User cannot jump headers.
Also, Japanese and Chinese are supported.
=> Add markdown-it-named-headers and adjust to use Japanese or Chinese

browser/components/MarkdownPreview.js, browser/lib/markdown.js
=> iss #809 normalize text works only in img tag

browser/components/CodeEditor.js
Use a function of CodeMirror instead of dom function
Ubuntu 16.04 LTS
The image link is not inserted on ubuntu
It succeeded.
* work on windows/mac
* insert appropriate position
=> Fix image insesration problem

browser/components/CodeEditor.js
I made pasting an image work.
Nothing happens when I paste an image.
I can paste an image from clipboard.
* does not work when I paste .pdf or something that are not images.
* Paste .png on macOS
* Paste .jpg on macOS
* Paste .png on windows
* Paste .jpg on windows
* Paste .jpg on Linux
* Paste .png on Linux
=> Make pasting an image in CodeEditor work

browser/main/Detail/InfoPanel.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js
I want word count and letter count in InfoPanel.
Neither word count nor letter count in both a Markdown note and a Snippet note.
In a Markdown note
In a Snippet note
* Appears appropriate word/letter count on Markdown Note
* Not appear on Snippet Note
* Not appear on Trash
The word count is not supported in Japanese and Chinese.
=> Add wordcount and lettercount to InfoPanel

browser/main/lib/AwsMobileAnalyticsConfig.js
When we open Boostnote, send AmazonMobileAnalytics event. its named 'MAIN_FOCUSED'.
=> add MAIN_FOCUSED event

browser/main/Detail/MarkdownNoteDetail.js, browser/main/NoteList/index.js, package.json, yarn.lock
I'd like to style my headings with a color. The problem is the HTML tags aren't stripped from the title. This PR fixes it.
Before:
After:
=> Strip HTML tags from the note title

browser/components/RealtimeNotification.js, browser/components/RealtimeNotification.styl, browser/main/StatusBar/index.js
We want users to notify tips.
I'm not sure how I describe plural notifications, so I managed to show the first notification of them `notifications[0]`
* it should not fail the application even if the notification repository does not exist
* it should show a notification
=> Add RealtimeNotification

browser/components/CodeEditor.js
We want to exit from the editor in Vim mode.
* :q exits from editor mode
* :q! exits from editor mode
* :qw exits from editor mode
=> iss #832 Make :q work in vim mode

browser/main/Detail/MarkdownNoteDetail.js
The letter count and word count are wrong.
=> iss #888 Fix letter count

browser/main/NoteList/index.js
Drag&drop on NoteList.
Nothing.
* Drag&drop 1 .md file
* Drag&drop 2 .md files
* Drag&drop 1 .md and 1 .txt file
* Drag&drop 1 .html file
* Drag&drop .pdf file (not work)
* Drag&drop on trash
* Not working if the storage is empty
=> Add file drop on NoteList

browser/components/RealtimeNotification.js, browser/components/RealtimeNotification.styl, browser/main/Main.js
This fixes the issue of the notification bar convering the "collapse" button of the navigation bar. See #904
=> Align notification bar with the navigation bar

browser/components/RealtimeNotification.styl
Change requested by @kazup01 while commenting #906
=> Place notifications on the right side of the notification bar

browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js, browser/finder/NoteDetail.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js
I love the "copy to clipboard" power of Boostnote within code blocks. However, as an end user, I don't really care for Boostnote to display a notification on copy.
**This PR adds a configuration option to disable these notifications! The new option is show below**
This is my first PR to **Boostnote**, please let me know if this commit needs amended.
=> Allow users to disable "Saved to clipboard" notification.

browser/main/Detail/TagSelect.styl
Mistake in code. Changed from `borde-box` to `border-box`.
=> Fix "borde-box" typo

browser/components/MarkdownPreview.js
A font with space in the name such as `Migu 1M` could not apply to font-family.
The font is not quoted.
Quoted.
=> Change to apply font with single quotations

browser/components/CodeEditor.js
This PR fixes pasting the image from clipboard.
The reason why the issue happened is that because there's no image directory on the storage.
ref: https://github.com/BoostIO/Boostnote/pull/818
=> Fix to create imageDir if it does not exist

browser/components/NoteItem.js, browser/main/NoteList/index.js
I wanted to add this feature because it is very convenient and easy-to-know note deleting way.
As SideNav's folder also can be renamed and deleted with rightclick(context menu), I thought deleting note is also can be made by right click as well and I(as daily user) really felt that way.
=> Add notelist right click(context menu) and delete note

browser/lib/search.js, browser/main/NoteList/index.js, browser/main/TopBar/index.js, tests/lib/search-test.js
This PR fixes a problem which IME doesn't work on searching.
Boostnote will support IME input (I checked working in Japanese keyboard and Chinese pin yin keyboard)
=> Improve searching

browser/lib/consts.js, browser/main/modals/PreferencesModal/UiTab.js
Fixes #896 
CodeMirror seems to have the two solarized themes within the
`node_modules/coemirror/theme/solarized.css`. So passing the string
"solarized light" and "solarized dark" to the editor theme appropriately
sets these themes.
The Boostnote app appears to be dynamically determining themes based
on the css files found within `node_modules/codemirror/theme/`.
So that's why there was just a single option of 'solarized' before.
The light and dark 'solarized' themes appear to be the *only* themes
that share a css style, whereas all other light and dark variarnt
themes get their own css file (ex: base16-dark.css and base16-light.css).
Weird!
=> Support for solarized dark and light themes

browser/main/Detail/InfoPanel.js, browser/main/Detail/MarkdownNoteDetail.js
I replace `.pdf export` on InfoPanel to `Print` because I don't think it will be implemented soon and we can export as .pdf via `Print`.
=> Replace pdf to print

browser/main/global.styl, browser/main/lib/dataApi/index.js, browser/main/lib/dataApi/reorderFolder.js, browser/main/lib/dataApi/updateFolder.js, browser/main/modals/PreferencesModal/FolderItem.js, browser/main/modals/PreferencesModal/FolderItem.styl, browser/main/modals/PreferencesModal/FolderList.js, browser/main/modals/PreferencesModal/StorageItem.js, browser/main/modals/PreferencesModal/StorageItem.styl, browser/main/store.js, package.json, tests/dataApi/reorderFolder-test.js, yarn.lock
Hi guys,
this is my first contribution to other github project and also first time I worked with react, so please be critical.
It is related to issue Rearrange storage #741.
Quick description:
From StorageItem extracted FolderList and FolderItem as separate components.
Wrapped them in the rect-sortable-hoc.
Implemented new data api method called reorderFolder.
I hope you will like it.
Cheers
Matus
=> Feature rearrange storage

browser/main/index.js
This fixes a bug where elements without a target offsetParent were throwing uncaught errors when trying to determine if a click event originated from an info panel element or not.
=> Fix: "Uncaught TypeError: Cannot read property 'className' of null"

browser/components/NavToggleButton.js, browser/components/NavToggleButton.styl, browser/components/StorageList.js, browser/components/StorgaeList.styl, browser/components/TagListItem.js, browser/components/TagListItem.styl, browser/main/NoteList/index.js, browser/main/SideNav/SideNav.styl, browser/main/SideNav/index.js, browser/main/TopBar/.#index.js, browser/main/index.js
implement tag area. Boostnote have Tag. However,It was meaningless. So, I implemented Tag Area.
We'll fix style.
(Japanese sorry...)
=> Feature tag area

browser/main/lib/AwsMobileAnalyticsConfig.js
**Reason for pull request**
Currently the app no longer works as expected when the app fails to connect to the analytics server as seen in issue #939. This pull request intends to fix that behavior.
**Fix**
Add a try/catch around the recording of events to ensure the app continues to work even when it cannot connect to the server. Log the error message in a clean way.
**Issues fixed**
This fixes #939
=> Add try/catch logic to recording of analytics events

browser/main/modals/InitModal.js
Missing "a" in sentence.
*"Quick search and copy the content of note" to "Quick search and copy the content of **a** note"*
=> Grammar fix

browser/main/SideNav/SideNav.styl, browser/main/SideNav/index.js
This PR resolve #982. 
I give height to the `.root` of  `SideNav`.
=> Fix #982: Tag list cannot be scroll

browser/main/NewNoteButton/NewNoteButton.styl
Converted postion from "fixed" to "absolute" and made the subsequent adjustments for it to appear.
=> Adjust tooltip (#963)

browser/main/lib/AwsMobileAnalyticsConfig.js
We want to know platform and Boostnote's version.
So, I added options to get information of platform and Boostnote's version to config file of ama.
=> enable to get appVerion and platformName

browser/components/SideNavFilter.styl, browser/main/SideNav/SideNav.styl, browser/main/SideNav/index.js
on v0.8.16, we added tagArea.
It cause some style bugs. I fixed these bugs.
When, we pushed NavToggle Button, 
* 1: background-color of storageList is white.
* 2: icon of PreferenceButton, AllNotesButton, StarredButton, and TrashedButton is disable.
* 3: There is a mystery space at the top of SideNav.
=> Fix side nav style

browser/main/SideNav/SideNav.styl
Fixed a bug in which the display of PreferenceButton was distorted depending on the size of the display.
=> start point of absolute to the right.

browser/main/Detail/SnippetNoteDetail.js, browser/main/lib/AwsMobileAnalyticsConfig.js
We can select languages to syntax highlight snippets.
We want to know languages that user selected.
So, I add AMA event for it.
=> Add ama event for snippet lang

browser/main/modals/PreferencesModal/ConfigTab.styl, browser/main/modals/PreferencesModal/HotkeyTab.js
1.  Adjust position of notification in HotKeyTab
2. Notification can disappear, to be more like a notification.
Would like to but break some test. For the moment, deleted feature in commit below.
=> Adjust notification HotKeyTab

ISSUE_TEMPLATE.md
We have to notice a user who tries to open an issue regarding boostnote mobile move to https://github.com/BoostIO/boostnote-mobile.
=> Change ISSUETEMPLATE to add a sentence dealing with if a user tries to open an issue regarding boostnote mobile

browser/components/markdown.styl, browser/lib/markdown.js, package.json, webpack-skeleton.js, yarn.lock
This feature solves #1015, adding `kbd` functionality by using `<kbd></kbd>` tags or `[[]]` syntax.
=> Add keyboard markdown

browser/main/Detail/MarkdownNoteDetail.js
As @piefel mentioned in https://github.com/BoostIO/Boostnote/issues/1009#issuecomment-339235083, it's not easy to understand the role of the lock button. So I changed the tooltip text.
=> Change the tooltip text of the lock button for easy to understand what its role

browser/main/modals/PreferencesModal/HotkeyTab.js
1. Notification can disappear, to be more like a notification.
=> ClearMessage notification HotKeyTab

browser/main/modals/PreferencesModal/ConfigTab.styl, browser/main/modals/PreferencesModal/InfoTab.js, browser/main/modals/PreferencesModal/InfoTab.styl, browser/main/modals/PreferencesModal/UiTab.js
1.  Adjust the message of note in UiTab:
2.  Add notification message for Data collection policy in InfoTab:
=> Adjust Note in Uitab && Add message notification for data policy save

browser/components/MarkdownPreview.js
After upgrading to 0.8.16, I failed customize Preview Font Family. I found the CSS rule below failed due to escaped quotation marks, causing font-family inherited to another rule.
```css
body {
font-family: 'Ubuntu','meiryo',''Microsoft YaHei'','helvetica','arial','sans-serif';
}
```
Removing the escaped quotation marks between `Microsoft YaHei` would solve the problem.
My environment is:
* OS: Ubuntu 17.04 x86_64
* node: v6.11.5
**Before**
**After**
with preview font set to `Ubuntu`
=> Fix custom preview fonts

browser/components/NoteItemSimple.js, browser/main/NoteList/index.js
Fixes #1034
I copied the code from the NoteItem context menu and added that to the SimpleItem. I couldn't find any tests for this behavior, so I left it for now.
=> added the context menu to the list view

browser/main/NoteList/index.js
For user friendly movement in terms of pin to top interfaces
=> Fix enabling no focus right click pin to top and show adequate context menu

browser/components/MarkdownPreview.js
Fixes #1040
The cause of the problem is in ```MarkdownPreview.js```. The function ```fixDecodedURI``` only checks for innerText for every anchor element, but doesn't check if the anchor element contains other elements. In that case the uri is not decoded and the node remains as is.
=> only decode the url when the content of the link is a string

browser/lib/markdown.js, package.json, yarn.lock
I integrate `markdown-it-plantuml`.
```
@startuml
Bob -> Alice : hello
@enduml
asdfsd
```
https://github.com/BoostIO/Boostnote/issues/771
This markdown-it plugin is a brand new one.
https://github.com/gmunguia/markdown-it-plantuml
=> Add PlantUML support

browser/main/NoteList/index.js
Fixes #983 
Previously the `sortByPin` function was getting the pinned notes then preprending them to *all* the notes, pinned notes included, meaning there were duplicate items in the `notes` array. This caused the "Next Note" functionality to not always work correctly (if the next note was in fact a duplicate of the selected note).
This fix filters the notes into "pinned" and "unpinned" then concatenates them together, avoiding duplicates.
=> Include each note only once when sorting by pin

browser/components/MarkdownPreview.js
fix #1060 
solarized dark/light shares the same css in CodeMirror.
You can see more detail info in commit 5b17808569eea3efc556d71f5c8b37d44cf5a295
We need to treat solarized as a special case in code block also.
=> fix solarized dark/light code block thema bug

browser/main/SideNav/index.js
Fixes #981
The tag got highlighted when the current pathname contained the tagname (so for pathname /tag/boostnote both boost and boostnote got highlighted). I changed this by checking the exact name of the tag in the pathname.
=> only make the selected tag active

lib/main-menu.js, lib/main-window.js
Fixes #997 
**Changes:**
- added a shortcut (like mentioned in the comments of the issue) CTRL/CMD+Q to quit the app.
- close the app (instead of minimize) when clicking the close button (could be changed in a setting in the future).
=> added shortcut ctrl+q for quit and quit the app when using the Windows Close button

browser/main/NoteList/index.js
fix #1057
Current implementation is fetching the import destination storageKey and folderkey from a file in the folder. If no files are in the folder, it cannot fetch these keys. Use prop.params.storageKey / folderKey instead.
=> enable importing file to empty folder

browser/components/SideNavFilter.js, browser/components/SideNavFilter.styl, browser/main/SideNav/index.js
* Add counter to see how many notes are in the trash.
=> Add counter on deleted notes

browser/main/SideNav/index.js, lib/main-menu.js
**Reference**
Fixes issues #916 and #1074 
**Description**
This pull request adds an option to open 'Preferences' to the menu. For Windows/OS X this is in the 'Boostnote' menu, for Linux in the 'File' menu.
**Screenshot/GIF**
=> [Improvement] - Option for preferences in menus (916 & 1074)

webpack-skeleton.js
```
./node_modules/grunt/bin/grunt pre-build
secret/auth_code.json is not found. CodeSigning is not available.
Running "pre-build" task
Running "compile" task
node_modules/.bin/webpack --config webpack-production.config.js
Hash: ccaf27ad4bf2df5d3c4b
Version: webpack 1.15.0
Time: 24077ms
+ 969 hidden modules
ERROR in main.js from UglifyJs
SyntaxError: Unexpected token punc «,», expected punc «:» [./~/markdown-it-plantuml/lib/deflate.js:6,0]
ERROR in finder.js from UglifyJs
SyntaxError: Unexpected token punc «,», expected punc «:» [./~/markdown-it-plantuml/lib/deflate.js:6,0]
Running "pack:osx" (pack) task
/Users/yoshi/src/github.com/yosmoc/Boostnote/dist
Packaging app for platform darwin x64 using electron v1.6.15
Done.
```
```
./node_modules/grunt/bin/grunt pre-build
secret/auth_code.json …
```
=> Fix grunt pre-build error

browser/components/MarkdownPreview.js, browser/main/lib/ConfigManager.js
fixup commit for 0bf7e8b705793f432545c204749526d457547552
Solarized light/dark shares the same css file 'solarized.css'. Split by a space and use first one, since "solarized light" and "solarized dark" are the only theme which has a space in the theme name.
=> solarized light/dark bug fix

package.json, yarn.lock
Today I investigate the #1090 problem, but unfortunately, I couldn't reproduce the problem.
According to this thread https://github.com/electron/electron/issues/9616, it has already been fixed in electron 1.6.x. So, I update electron to latest stable version.
And electron-prebuilt is obsolete. So I use latest electron instead. 
I have built in Ubuntu 17.10 in my Virtualbox and it seems working fine.
Would some one try this PR?
=> electron-prebuilt is obsolete. use latest electron instead

browser/components/CodeEditor.js
As an avid vim user, I often use "ZZ" while in normal mode to quickly save and exit. This PR makes that bit of vim functionality work in Boostnote as well.
=> make ZZ work in vim mode

browser/components/CodeEditor.js
Checkbox type item list is not supported for list indentation by tab key.
I would like to be able to make possible this. Is this specification is accepted?
=> Add task item to indent adjustment target for list

browser/components/CodeEditor.js
fixes issue #1086 - only paste the created image tag over the current selection, not the start and end of the whole textarea.
=> replace selection with pasted image

gruntfile.js, package.json
Hi, 
I'm usually use Fedora, so I happy if the official rpm  package will be provided in the future.
This PR make it able to build rpm package using [grunt-electron-installer-redhat](https://www.npmjs.com/package/grunt-electron-installer-redhat).
I confirmed with Fedora and Ubuntu that the build will succeed with this change.
[This is Dockerfile I used for test build.](https://gist.github.com/kazuhisya/98e8f480d5edfcf50cc52755c352ebb0) and you can check the details by `docker build` this.
I'd happy it if you could review. Thank you!
Related: #5
Signed-off-by: Kazuhisa Hara <kazuhisya@gmail.com>
=> add rpm support

browser/main/modals/PreferencesModal/InfoTab.js, browser/main/modals/PreferencesModal/Tab.styl, browser/main/modals/PreferencesModal/index.js
=> Add community on tab in preferences

lib/main.html
Hi. Thanks for Boostnote. It's very useful.
but, Boostnote can't syntax highlight Rust. CodeMirror need simple addon for the Rust.
=> Add simple addon for CodeMirror

browser/components/NoteItem.styl
=> Fix layout at note item

docs/build.md, docs/debug.md, docs/fr/build.md, docs/fr/debug.md
Added the translation for French.
I added the link in the EN files, but not in jp, ko, ru and zh, since I don't know how to reference it in those languages.
=> Add fr /docs translations

browser/main/Detail/MarkdownNoteDetail.styl
=> Fix Margin at Note Detail

browser/components/SideNavFilter.styl
When SideNav is folded, there is no background-color when I hover on an item
Before : 
So I added a background-color in order to see better what the SideNavItem is about
After :
=> SideNavItem: add background when hover

lib/main-window.js
Boostnote ~never stores~~ always resets the window size on Ubuntu.
I noticed that `mainWindow.getBounds()` in `storeWindowSize()`, which is called on `window-all-closed` event ([lib/main-window.js](https://github.com/BoostIO/Boostnote/blob/29fa512a90d1cee974d62fed46d4f43293e23df8/lib/main-window.js#L64,L76)),  always returns `{ x: 0, y: 0, width: 0, height: 0 }`.
Handling [`before-quit`](https://github.com/electron/electron/blob/master/docs/api/app.md#event-before-quit) event or [`will-quit`](https://github.com/electron/electron/blob/master/docs/api/app.md#event-will-quit) event doen't fix either.
I'm not sure if this makes sense but `storeWindowSize()` on `close` event works.
* Ubuntu 16.04.3 LTS
* Boostnote 0.8.16
* [fix quit bug on Ubuntu · …
=> store correct window size on Linux

browser/components/SideNavFilter.styl, browser/components/StorageItem.styl, browser/main/SideNav/SideNav.styl, browser/main/SideNav/StorageItem.styl
=> Fix folded layout

browser/components/RealtimeNotification.styl
Hi :)
Suggestion about the problem with the notification area, she is now top-left.
Tell me what do you think :)
=> Correction Notification top-left

browser/main/Detail/TagSelect.js
When user inputs the tag and leave the tag input box without fixing(enter or tab key), tag string is still there, but it is not stored as a tag.
This PR solves this problem. When the cursol is out of the tag input, it registers the current input contents as a tag.
=> confirm tag at onBlur event

browser/main/modals/PreferencesModal/UiTab.js
Hi :)
* **Bug fix**
[React-codemirror library](https://github.com/JedWatson/react-codemirror) produced a bug with the ```loadModule()``` method.
The mini editor inside the UI tab was not highlighted when the component was mount for the first time due to an error with react-codemirror.
=> Fixbug react code mirror

browser/lib/markdown.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js, yarn.lock
See [https://github.com/BoostIO/Boostnote/issues/1201](https://github.com/BoostIO/Boostnote/issues/1201). This add optional LaTeX delimiters. 
However, currently this has a bug that LaTeX preference value seems not to be saved but I cannot understand. I want help to solve.
=> Add custom LaTeX delimiters to preferences

browser/components/markdown.styl, browser/lib/markdown.js
A really small PR to have a better style on checked items (before on the left). Simple but easier to find uncompleted items in a todo list 😉
=> Add a specific style for checked inputs

browser/components/NavToggleButton.styl
At the moment when you hover the left menu icon its hard to see that you fully hovering it, yes there is a white color and a cursor icon I was thinking it would be useful to have a more visual effect
Folded out:
Folded in:
White theme:
=> Added border radius & background color to NavToggleButton 

lib/main-menu.js
=> added ctrl+, shortcut to preference modal

browser/main/modals/PreferencesModal/StoragesTab.js
[Cloud-Syncing](https://github.com/BoostIO/Boostnote/wiki/Cloud-Syncing) link in `Preference > Add Storage` seems to have been renamed.
I'd say it should point to [Cloud-Syncing-and-Backup](https://github.com/BoostIO/Boostnote/wiki/Cloud-Syncing-and-Backup) now.
related to #889
=> Fix link to Cloud-Syncing

browser/components/CodeEditor.js, browser/components/MarkdownEditor.js, browser/finder/NoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js, lib/main.html
Implements feature request in #838. This is something I missed from the editor, as well.
CodeMirror has a `scrollPastEnd` addon and I just added a checkbox in the UI tab of Preferences to enable it in the code editor.
=> Add scroll past end

browser/lib/getTodoStatus.js, tests/lib/get-todo-status-test.js
=> Fixed regex to stop [anytingx] being counted as a checkmark

browser/components/NoteItem.styl, browser/components/RealtimeNotification.styl, browser/components/TodoListPercentage.styl, browser/components/markdown.styl, browser/finder/FinderMain.styl, browser/finder/NoteDetail.styl, browser/main/Detail/Detail.styl, browser/main/Detail/MarkdownNoteDetail.styl, browser/main/Detail/NoteDetailInfo.styl, browser/main/Detail/TagSelect.styl, browser/main/SideNav/SideNav.styl, browser/main/SideNav/StorageItem.styl, browser/main/global.styl, browser/main/modals/PreferencesModal/ConfigTab.styl, browser/main/modals/PreferencesModal/Crowdfunding.styl, browser/main/modals/PreferencesModal/FolderItem.styl, browser/main/modals/PreferencesModal/InfoTab.styl, browser/main/modals/PreferencesModal/PreferencesModal.styl, browser/main/modals/PreferencesModal/StoragesTab.styl, browser/styles/index.styl
Add Solarized Dark theme
@kazup01 Check it plz
=> Add Solarized Dark theme

browser/components/NoteItemSimple.js, browser/components/NoteItemSimple.styl, browser/main/NoteList/index.js
=> Add Pin to NoteItemSimple

browser/main/NoteList/index.js, browser/main/lib/dataApi/createNote.js
NB: this definitely works on OSX. Other operating systems may have
slightly different interpretations of (eg) birthtime.
See: https://nodejs.org/api/fs.html#fs_class_fs_stats
=> Use existing file metadata for created and modified dates

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/MarkdownNoteDetail.styl, browser/main/Detail/TagSelect.styl, resources/icon/icon-WYSIWYG-off.svg, resources/icon/icon-WYSIWYG-on.svg, resources/icon/icon-code-off.svg, resources/icon/icon-code-on.svg
Added a note mode tab to switch WYSIWYG to preview&markdown mode.
=> add note mode tab

browser/main/Detail/FullscreenButton.js, browser/main/Detail/FullscreenButton.styl, browser/main/Detail/InfoButton.js, browser/main/Detail/InfoButton.styl, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/MarkdownNoteDetail.styl, browser/main/Detail/PermanentDeleteButton.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/StarButton.js, browser/main/Detail/StarButton.styl, browser/main/Detail/ToggleModeButton.js, browser/main/Detail/ToggleModeButton.styl, browser/main/Detail/TrashButton.js, browser/main/Detail/TrashButton.styl, browser/main/SideNav/ListButton.js, browser/main/SideNav/PreferenceButton.js, browser/main/SideNav/PreferenceButton.styl, browser/main/SideNav/SideNav.styl, browser/main/SideNav/SwitchButton.styl, browser/main/SideNav/TagButton.js, browser/main/SideNav/index.js
(and consequently extracted some buttons and styles)
Fixes #1311
=> added tooltips like the new note button

browser/main/NoteList/index.js
This PR restores the ability to jump to other notes from links within markdown notes. This functionality was broken because we were routing to the hash of the currently visible note, rather than routing to the hash of the new note. 
Thanks for the opportunity to help with a quick bug fix! What a great way to spend a flight 😄 
Closes #1315
=> Fix linking to other notes

browser/components/MarkdownPreview.js, browser/main/Detail/InfoPanel.js, browser/main/Detail/InfoPanelTrashed.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, lib/main-menu.js
minimum viable implementation of #1233, please let me know what you think.
=> first attempt to export html

browser/main/StatusBar/index.js, browser/main/modals/PreferencesModal/ConfigTab.styl, browser/main/modals/PreferencesModal/HotkeyTab.js, browser/main/modals/PreferencesModal/PreferencesModal.styl, browser/main/modals/PreferencesModal/Tab.styl, browser/main/modals/PreferencesModal/UiTab.js, browser/main/modals/PreferencesModal/index.js
Hi :) 
- Add new features on **Preferences settings**, concerning the **Ui Tab** and  **Hotkey Tab**:
When the configuration settings is changing but you didn't saved yet, it tell you that is not saved yet.
=> Add notification on change ui

browser/components/markdown.styl
=> add table style in solarized-dark-theme

.gitignore, browser/main/SideNav/StorageItem.js, browser/main/lib/dataApi/exportFolder.js, browser/main/lib/dataApi/index.js, browser/main/store.js, tests/dataApi/exportFolder-test.js
=> export folder as md or text

browser/components/CodeEditor.js
Closes #1358 
Bug was introduced here: https://github.com/BoostIO/Boostnote/commit/3fbc749395b7c90643d05ee09b8e7f74e00eb190#diff-4771352a7e4e4f9d82f0be3e914757adL245
=> fix(code-editor): use correct prop for font family

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/index.js, browser/main/modals/PreferencesModal/UiTab.js
=> show delete confirmation dialog

browser/components/CodeEditor.js, lib/finder.html, lib/main.html
I implemented one of the #1390 with a codemirror addon.
You enter a bracket, editor close a bracket automatically.
=> Cm close brackets

lib/main-app.js, package.json, yarn.lock
- Fix windows update #1239 
- Upgrade grunt-electron-installer
- Check update after 10 secs from launching to prevent from file locking
- Check update every day rather than every hour #1309
=> Fix windows update

browser/main/modals/CreateFolderModal.styl, browser/styles/index.styl
=> fix bug happen on solarized-dark CreateFolderModal.

browser/main/lib/dataApi/exportFolder.js
`writeFileSync` doesn't require a callback.
=> Fix exportFolder error

browser/components/markdown.styl
=> Remove inline-style from markdown link list

browser/lib/markdown.js
fixes #1270
Convert the input string to utf-8 with `unescape(encodeURIComponent(umlCode))`, directly copied from [plantUML Web Server](http://www.plantuml.com/plantuml/uml/ZP51JWCn34NtFeLtJA_GggAZAK9TWBf1h4t6qub8an8xBUs9k0SNmpDK55Kis4NEz_VxzaAKifPjWF41cNTC2jDxLdmIpf6sZ7LiSKqYXvJR6SIaZ84xXUUUC-Cwit1Kma0epafRKeBMOqWR7v52k2bg0WOsdw4RV8VLZ_jyZb8_rCwb4lNHAXFKdYDMHvO9J9kUtUlVB0ZrXdmKnTgftpCkVMQdAHz_Kwu2MlEUCnhJjH0-Ft17sPmr-zE9D65B-5OeM184-p8RAJX6lGJW88nLJF_b-zxK8CAbRUU5XC-8sMzwXIP5AMp3kr14qa0AD6xDEphv57aeNKF4rdSmlNjdPr8SGMRd2-AXzy4GLtAXQL8UKjzExDPf1mlhjyD_0G00): 
```javascript
function compress(s, change) {
//UTF8
s = unescape(encodeURIComponent(s));
dest = "http://www.plantuml.com/plantuml" + "/uml/"+encode64(zip_deflate(s, 9));
if (change) dest += "?switch";
window.location.href = dest;
}
```
=> convert uml to utf8 before converting to base64

browser/finder/index.js
Hi, this fixes #1238. If the e.metaKey swallow was placed there for a reason then please let me know and I can look into a different approach. 
Thanks!
=> Allows keyboard text selection in Finder search box

browser/main/Detail/FolderSelect.styl, browser/main/Detail/FullscreenButton.styl, browser/main/Detail/InfoButton.styl, browser/main/Detail/InfoPanel.styl, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/MarkdownNoteDetail.styl, browser/main/Detail/NoteDetailInfo.styl, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/SnippetNoteDetail.styl, browser/main/Detail/StarButton.styl, browser/main/Detail/TagSelect.styl, browser/main/Detail/ToggleModeButton.js, browser/main/Detail/ToggleModeButton.styl, browser/main/Detail/TrashButton.styl, browser/main/StatusBar/StatusBar.styl, browser/main/global.styl, browser/styles/index.styl, resources/icon/icon-full.svg, resources/icon/icon-info.svg, resources/icon/icon-mode-markdown-off-active.svg, resources/icon/icon-mode-split-on-active.svg, resources/icon/icon-star.svg, resources/icon/icon-starred.svg, resources/icon/icon-trash.svg
=> WIP - Fix info right buttons layout

browser/main/Detail/TagSelect.js
- Remove leading # from tags that are created with leading # (user types in `#tagName`)
- Convenience method for users who tend to type them, but did not want a tag with two #
- If a user wants a tag with a leading #, then can enter `##OfPeople`, and only the first will be removed
- Resolves #1476
=> Remove leading # when creating tag

browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js, browser/components/MarkdownSplitEditor.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js
With regards to #1471... Here's a PR from a complete novice when it comes to the Electron and React world, hope it's not *too* bad. I'm open to learning to the correct way of doing things if you'd be so kind as to point me in the right direction. Anyhow, this worked for me
=> Allow preview area to scroll past end of file

browser/components/MarkdownPreview.js, browser/components/markdown.styl, browser/lib/markdown.js, browser/lib/utils.js
I've noticed that some styles applies directly to  HTML in `rewriteIframe` method of MarkdownPreview component. It's not a good practice, so I removed that.
I add class to the li tag at transformation from markdown to html stage and then style it with css.
=> Remove direct css styling todo lists from MarkdownPreview component

browser/components/CodeEditor.js, lib/main.html, node_modules/boost/boostNewLineIndentContinueMarkdownList.js
On the enter key pushed, if already the line contains a token in markdown list, no completion is needed, I think.
For example, if I push the enter key when md is like below, and my cursor selects the head of the line,
```
```
the behavior before
```
```
the behavior after.
```
```
By this change, node_modules/codemirror/addon/edit/continueList.js could be trashed, but I can't because of the gitignore.
=> I fixed the behavior of the editor when the enter key is pushed.

browser/main/NoteList/index.js
This gives a more native feel to it and is more helpful to users to quickly get used to the app without clicking on the buttons:
Before commit changes (when hovering):
After commit changes (when hovering):
More examples
=> Added title attributes to elements to show information on hover --- more like a native app feel to it

browser/main/SideNav/index.js
The selected note category count should equal the amount of notes visible in the note list. Currently, trashed notes are counted as notes, but are not visible, so the counts don't add up.
This PR fixes that.
=> Trashed notes should not be counted

browser/main/NoteList/index.js, browser/main/modals/NewNoteModal.js
This PR fixes two UX bugs:
1. The visible note should always be selected or part of a selection.
1. When navigating from a set to a superset or vice-versa, the visible (selected) note should not change if it's part of both sets.
Previously, it was confusing to follow what's going on, because the selection and note visibility were not synced. This demonstrates the old behavior. **Play close attention to the note in view on the right, and the selection in the note list:**
With this PR, the selected note will remain selected as long as it's part of the subset (e.g. when searching or changing storage), and if not, when the first note is automatically viewed (old behavior) the selection will be updated to match:
=> UX: Keep selection synced with note visibility

browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js, browser/main/modals/PreferencesModal/UiTab.js
User want to click markdown to work with text (for example copy).
If they have "Switch to Preview" setting in "When Editor Blurred",
they enter edit mode after click. To fix that issue I introduced new
value to the "Switch to Preview" setting that do that thing. User can
enter edit mode by double click on the editor and leave it on blur.
Unfortunately, it's impossible to switch both ways by double click
because the editor mode is listening for double click event.
#1523
=> Switch from preview to edit by double click

browser/components/CodeEditor.js, browser/components/MarkdownPreview.js, browser/components/MarkdownSplitEditor.js
I have created a low impact delayed debounced scroll sync for the split editor.
This could probably be done better with some modules that allow queueing and animation in order to better catch missed events from rapid scrolling, but I know absolutely nothing about react, so I coded this moon-lander-style. That said, it's already infinitely better than nothing.
This would close #1355.
=> Sync Split Editor scroll position

browser/main/Detail/MarkdownNoteDetail.js
There is no `componentDidUnmount`.
=> Fix memory lickage

browser/components/CodeEditor.js, browser/main/TopBar/index.js
I like to see the global search matches in the markdown editor for productivity reasons. I implemented this for personal use, and I hope it will be useful to others.
This partially addresses #755.
This PR makes it more evident that the global search box could really use both an "x" symbol that appears to clean/delete the current input (for touch users) or having the escape key clean the input (for keyboard users), but that is beyond the scope of this PR. See #1525.
=> Highlight global search matches on code editor

browser/components/markdown.styl, browser/lib/markdown.js
! Please reject my former pull request !
I've added a feature displaying file name in code block.
Additionally, I made it possible to define any first line number.
The notation is as follows.
<pre>
```[Language]:[File Name]:[First line number]
```
</pre>
Example:
<pre>
```html:something.html:10
&lt;body&gt;&lt;/body&gt;
```
</pre>
If you don't write file name and line number, it behaves originally.
=> Display filename in codeblock (resend)

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/RestoreButton.js, browser/main/Detail/RestoreButton.styl, browser/main/Detail/SnippetNoteDetail.js, browser/main/NoteList/index.js
It solves issue #1325. I decided not to change the icon, but enhance UX at the Trash view.
1. RestoreButton component was added. The button has tooltip (tiny part of issue #1311)
2. Added "Restore note" item to the context menu in the Trash view
=> Restore note UX enhancements

browser/components/SideNavFilter.js, browser/main/SideNav/index.js
Feature request from #1555 
I was contemplating to add a window to allow the user to "confirm" the deletion, but I think that wouldn't be needed since the user already technically "confirmed" that decision when deleting a single note beforehand. Apps nowadays don't really give the user any notification of emptying the trash anyways because 99% of the time the user never really empties the trash on accident. nor would the notes being deleted from the trash be of importance anyway, being the reason they got there in the first place
=> Added option Empty Trash

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/MarkdownNoteDetail.styl, browser/main/Detail/ToggleModeButton.styl
Fixes #1564
The absolute positioning of the toggle mode button was creating a static overlapping position issue with the top bar. This fix solves that problem by removing the static positioning and coupling the button component with the buttons to the right (which I think is more appropriate by looking at how it is presented)
=> Fixed ToggleMode button overlapping CSS issue

browser/components/NoteItem.js, browser/components/NoteItem.styl, browser/components/NoteItemSimple.js, browser/components/NoteItemSimple.styl, browser/main/NoteList/index.js
Added storage labelings to 'All Notes' (this serves as a starting point for building the rest of #1545)
Works for:
- Default view
- Compressed view
Previously when we were viewing notes in the All Notes view, we could not tell which storage the notes came from. This was confusing to the user. So we need a way to show to the user which storage the notes are in. This pull request provides storage labels to solve that as shown in the screenshot below
This is a re-make in reference to #1551 and originated from #1545  without any color integration implemented, with the purpose of serving as a starting point
I re-made the pull request to make this more simple because the previous pull request had unrelated changes (it barged into the folder labelings when this was originated for storage …
=> Add storage labels to 'All Notes' and figure a better solution to the dull storage notes list view

browser/components/NoteItem.js, browser/main/NoteList/index.js, browser/main/lib/ConfigManager.js, browser/main/lib/dataApi/updateNote.js, browser/main/modals/PreferencesModal/Blog.js, browser/main/modals/PreferencesModal/index.js
https://github.com/BoostIO/Boostnote/issues/1571
Scope:
This PR aims to allow users publish `markdown` notes to configured wordpress sites. Snippets are not supported (we should probably allow publishing them to gist)
Feature:
- Publish Markdown document to Wordpress blog
- 2 Authentication methods are supported [JWT token ](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) or [WP-API basic auth](https://github.com/WP-API/Basic-Auth)
- Update published Blog
- Open published Blog
Requirements
- Wordpress rest api [doc](https://developer.wordpress.org/rest-api/)
- Authentication in wordpress
Screenshots:
- Configuration
- Context Menu (Unpublished Markdown)
- Context Menu (Published Markdown)
- Publish Confirmation
- Publish failure comfirmation
- Published Blog Sample
=> allow publishing markdown to wordpress

browser/main/SideNav/StorageItem.js, browser/main/lib/dataApi/copyImage.js, browser/main/lib/dataApi/exportNote.js, browser/main/lib/dataApi/moveNote.js
1. Added new step of moving note's images to `moveNote` function
2. Changed behavior of sidebar navigation after move finished
#1578
P.S. We should refactor moveNote function soon: all operations there are synchronous and we don't process errors at all
=> Move images between storages together with note

browser/main/NoteList/index.js
Resolves #1582 
This will reduce user time and increase productivity by quickly copying  note links directly from the note list rather than having to go to the note details and the info panel to do it themselves
=> Adds the ability to copy the note link from the note list

browser/styles/index.styl
Fixes #1580 
UI overlapping in the snippet editor (bottom options)
=> Fixes UI overlapping in the snippet editor (bottom options)

browser/components/CodeEditor.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/NoteList/index.js, browser/main/TopBar/TopBar.styl, browser/main/TopBar/index.js, lib/main-menu.js
* Search: Esc clears the search
* Search: Add search clear button
* Search: Select previously entered search word so you don't have to manually backspace
* Search: Added Ctrl+F (find) synonym for Ctrl+S (search) as most other apps use F.
* Unless code editor is focused, because it uses Ctrl+F internally.
* Search: Allow up/down prev/next note while searching
* Notelist: Added j/k synonyms for up/down
* Ctrl + j and ctrl + k are mapped as previous/next note in menu, so j and k should have the same function in note list in order to keep things intuitive
=> Add search tweaks; closes 1525 closes 1167

browser/main/StatusBar/StatusBar.styl
Fix for #1598.
Zoom button got removed by this [PR](https://github.com/BoostIO/Boostnote/pull/1453) due to the new button toolbar layout. 
Revert the changes in `/browser/main/StatusBar/StatusBar.styl`.
=> fixed missing zoom button - #1598

browser/lib/markdown-it-sanitize-html.js, browser/lib/markdown.js, package.json
This will address #1443 at least partially by restricting the type of html tags and attributes that user is allowed to use.
`markdown-it` themselves [advise against enabling html](https://github.com/markdown-it/markdown-it/blob/master/docs/security.md) (and it was not my choice to enable it(1)), but I've seen youtube-iframes and img-tags used in the wild.
The set is pretty restrictive because I don't know what kind of html is legitimately used in the wild. This PR is **an important first step** and more tags can be allowed later if they turn out to be used by a lot of people. I _recommend to merge this first_ because it's a security issue, and wait for upset people that want to use html tag x-y-z later, and consider adding them back one by one.
---
(1): I think no html should be allowed. …
=> SECURITY HOTFIX - Remove XSS attack

browser/components/MarkdownPreview.js
The export to HTML feature was not including the `﻿<meta charset="UTF-8">` tag in its `<head>`, resulting in character rendering issues as described in #1624.
This commit adds that missing tag.
=> add UTF-8 tag to HTML export (fixes #1624)

browser/components/MarkdownPreview.js
Add "viewport" meta-data to HTML export.
See #1442 for details.
=> Export responsive html, fixes #1442

browser/components/MarkdownPreview.js, browser/lib/markdown.js
Quick and dirty fix for #1609.
__Code block in editor__
__Code block in exported HTML__
I will make some tweaks to the render function as lots of functionalities are missing in `handleSaveAsHtml` function, such as syntax highlight, code block theme (dracula), HTML entities #1647.
It would be a good idea to use the same render function in `rewriteIframe` and `handleSaveAsHtml` to keep everything consistent and most importantly, DRY.
=> fixed code block style in exported HTML file

browser/main/SideNav/index.js
Resolves #1608 
I don't think there was any good reason to have the tags un-sorted in comparison to being alphabetically sorted, so this should be a positive change
=> Sort tags alphabetically

browser/components/StorageItem.js, browser/main/SideNav/StorageItem.js, browser/main/SideNav/index.js
Resolves #1569 
Previously we could not re-order folders in the side nav. The only way we could do this is to manually go to the preferences and do it there. With this change, we are now able to drag folders and re-order them outside the preferences window. 
This change will decrease user time and increase productivity by quickly allowing the user to go back to what they were doing.
The folder-icon (and only the folder icon), when clicked and held, enables the folder to be moved.
=> Folders in the side nav are now draggable

tests/fixtures/TestDummy.js
Fix #1562 
At least two dummy folders/notes are required for reordering folders and moving notes in the test. Current dummy data implementation might result in generate only one folder / note.
Please see code below.
[TestDummy.js](https://github.com/BoostIO/Boostnote/blob/master/tests/fixtures/TestDummy.js#L25)
```js
var folderCount = Math.floor((Math.random() * 5)) + 1
/* ... */
var noteCount = Math.floor((Math.random() * 15)) + 1
```
However, following tests access to the second item in the folders/notes array.
[reorderFolder-test.js](https://github.com/BoostIO/Boostnote/blob/master/tests/dataApi/reorderFolder-test.js#L27)
```js
const secondFolderKey = t.context.storage.json.folders[1].key
```
[moveNote-test.js](https://github.com/BoostIO/Boostnote/blob/master/tests/dataApi/moveNote-test …
=> Changed the minimum count of dummy data (folders and notes)

package.json, yarn.lock
New stable version 0.9.0 is now released. It includes many improvements.
=> Update KaTeX Library from 0.8.3 to 0.9.0.

browser/components/MarkdownPreview.js, browser/components/NoteItem.js, browser/components/NoteItemSimple.js, browser/lib/keygen.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/index.js, browser/main/NoteList/index.js, browser/main/SideNav/index.js, browser/main/lib/dataApi/createNote.js, browser/main/lib/dataApi/moveNote.js, browser/main/modals/NewNoteModal.js, browser/main/store.js, package.json, tests/fixtures/TestDummy.js, yarn.lock
This PR is a suggestion to resolve #1623. It changes the hash (and filenames) for notes from 20 character hash to an uuid. 
Filename before: ```fc16de274b5ac2d604ed.cson``` new filename ```ce53287e-a77c-49c1-9d41-5d9fb0d60a3b.cson``` the change is backwards compatible. Old filenames can still be loaded. 
Note: it will break in very rare cases if you have the same filename/hash in multiple stores.
Not only in links but also inside the application the combination of storage.key and note.key was used. Multiple times both keys were concatenated and split again. I also removed this because the uuid is global unique and not by storage. The same applies to folders, but that's not in the scope of this PR.
=> remove volatile hash from note links - #1623

browser/lib/markdown.js
Fixed missing classname in lib/markdown due to the same file was modified in multiple commits. Related to #1609
=> fixed missing classname in lib/markdown highlight render function

browser/components/StorageItem.js, browser/components/StorageItem.styl
Improvement for #1661 
Instead of change the mouse style when hovering on folder icon, I added a new drag handle by the folder icon.
However, the draggable icon will not shown if you switch to collapsed menu mode, it would be too crowded if I put the draggable icon there. 
Any suggestions are welcome.
Thanks
=> Added draggable folder handle #1661

browser/components/NoteItem.js, browser/components/NoteItem.styl
=> Fix note list UI

browser/main/NoteList/index.js
fixes "copy note link from note list" introduced in #1583 to reflect changes from #1636
=> fix "copy note link from note list" link format

browser/main/NoteList/index.js
=> hotfix: update markdown render in blog post feature

browser/lib/markdown.js, browser/main/NoteList/index.js
Hi @lijinglue,
the default smart quote setting of `lib/markdown` was `true` and didn't follow global config in ConfigManager. I have modified `lib/markdown` to use `config.preview.smartQuotes` value as default. 
`markdown` instance was created at the beginning in `NoteList/index.js` and never reloads, when user changes `Smart Quotes` setting, markdown instance in `NoteList/index.js` won't be updated.
So I changed the markdown init behavior to only initiate when it's needed for `Post to Blog` feature.
**Before:**
**After:**
=> Fixed smart quotes when posting a note to blog

browser/main/NoteList/index.js
"Copy Note Link" generated by Context Menu at NoteList did not work.
before:
after:
=> Fix Copy Note Link in Context Menu

browser/main/lib/dataApi/exportFolder.js, browser/main/lib/dataApi/exportNote.js, package.json, yarn.lock
Fixes #1613 
I've added one more dependency `filenamify` (we can remove it if needed, the idea behind that module is very simple). I replace forbidden characters with a ground sign `_`.
=> Fix filenames with forbidden symbols during export #1613

browser/components/CodeEditor.js
closes #1680
When pasting URL to inside of a link tag, the title not fetched anymore.
=> Prevent generating a link tag when pasting URL to inside of a link tag.

browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js, browser/components/MarkdownSplitEditor.js, browser/lib/markdown.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js, locales/da.json, locales/de.json, locales/en.json, locales/es.json, locales/fr.json, locales/ja.json, locales/ko.json, locales/no.json, locales/pl.json, locales/pt.json, locales/sq.json, locales/zh-CN.json, locales/zh-TW.json
=> Make sanitization configurable

browser/main/Detail/FolderSelect.js, browser/main/Detail/FullscreenButton.js, browser/main/Detail/InfoButton.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/StarButton.js, browser/main/Detail/TagSelect.js, browser/main/NewNoteButton/index.js, browser/main/NoteList/index.js, browser/main/SideNav/StorageItem.js, browser/main/SideNav/index.js, browser/main/modals/CreateFolderModal.js, browser/main/modals/NewNoteModal.js, browser/main/modals/PreferencesModal/Blog.js, browser/main/modals/PreferencesModal/FolderList.js, browser/main/modals/PreferencesModal/HotkeyTab.js, browser/main/modals/PreferencesModal/StoragesTab.js, browser/main/modals/PreferencesModal/UiTab.js, browser/main/modals/RenameFolderModal.js
Prepared text for translation.
=> Update text for internationalization

lib/main-window.js
excluded the cinnamon desktop for the macOS-like behavior which closes the window, but does not shutdown the app processes as discussed in #1738 with @Rokt33r
=> fix incorrect app closing for linux mint cinnamon

browser/components/MarkdownPreview.js, browser/lib/utils.js
Export to HTML used to export html-like text in the note as is. The content of the note could disappear because of that. 
I've added a util function `escapeHtmlCharacters` and use it before export. The function convert symbols `"'&<>` to theirs html representation: `&quot;`, `&#39;`, etc.
Fixes #1728
=> Escape html characters before convert to HTML

browser/main/SideNav/index.js
The currently selected tag was not highlighted in the list.
Before:
After:
=> Fix highlighting of active tag

browser/components/CodeEditor.js, browser/main/global.styl, lib/main.html
This PR adds (much needed 😄) Code folding functionality to `code editor` by passing additional `options` to the `CodeMirror`
=> Add folding to CodeEditor

browser/main/lib/dataApi/resolveStorageNotes.js
related #1597 #1485 #1694
I also have same behaviour reported in above issues. 
I don't know broken .cson error is made by Boostnote or not, but it is quite scary that notes seems to be disappeared. Investigating the reason why we get the broken the .cson is important, but I think quick fix is more important. 
In current implementation, when .cson is broken and catch error in processing this file,  undefined is collected in notes. If undefined is in the notes, we cannot see the broken note and following notes even they are not broken.
My implementation is just removing undefined from  the note list.
=> remove broken note from note list

browser/main/NoteList/index.js, browser/main/TopBar/index.js, browser/main/index.js
This PR fix reloading creash on `/searched` #1743
Add routing for search word:
- `/searched/:searchword`
Restore the state from the `:searchword` params.
fix #1743
=> fix reload crash on /searched

browser/lib/i18n.js, browser/main/lib/ConfigManager.js
Fixes #1761 (part 1)
Fixes #1727 (there are still *.pak files in locales folder, but .json files aren't necessary)
Tested with "grunt pre-build" on mac os 10.13.3 and win 10
=> Fixed change language in production mode

.babelrc, __mocks__/electron.js, package.json, tests/components/TagListItem.snapshot.test.js, tests/components/__snapshots__/TagListItem.snapshot.test.js.snap, tests/jest.js, yarn.lock
I've added Jest to the project. 
There is an issue when you test components with external js libraries. For example, `MarkdownPreview` works with `Raphael` and its' extensions to draw graphs. I haven't figured out yet how to mock these stuff properly.
=> Add jest and simple test

.boostnoterc.sample, browser/main/SideNav/SideNav.styl, browser/main/SideNav/index.js, browser/main/lib/ConfigManager.js, locales/en.json, locales/hu.json, tests/lib/boostnoterc/.boostnoterc.all
=> Add selector to sort tags by counter or alphabetically

browser/lib/search.js, tests/lib/search-test.js
Some issues introduced in #954 (https://github.com/BoostIO/Boostnote/pull/954#issuecomment-336344915):
- search by `#tag1 #tag2` returns the results of only `#tag2`
- search by `#tag1 content` is as same as AND search by `#tag1 content` (and `#tag1` is regarded a word, not a tag)
- search by `content #tag1` returns the results of only `#tag1`
This commit fixing these:
- search by `#tag1 #tag2` returns the results of only `#tag2`
- search by `#tag1 content` is as same as AND search by `#tag1 content` (and `#tag1` is regarded a word, not a tag)
- search by `content #tag1` returns the results of only `#tag1`
NOTE: the examples works without `#` character too, because `findByWord()` checks the tags too.
* #1499 
* #1683
=> Fix tag filtering in search entry

browser/main/index.js
Hi boostnote team,
This is a fix for the issue https://github.com/BoostIO/Boostnote/issues/1808
Basically, this PR help prevent the top menu to appear when you hit the alt key with other key (like alt + arrow key to switch workspace on linux) or with mouse click to avoid conflict with boostnote shortcut but also enable user to toggle top menu by only pressing the alt key.
=> fixed menu popup on alt key pressed

browser/components/TagListItem.js, browser/components/TagListItem.styl
If a tag has a number in the name or there are a lot of notes with a tag the current count of notes in a tag can be confusing with a single space between the tag name and the count.
This update borrows the styling from the storage item to float the count to the right side of the sidebar.
=> Updated tag note count to float to the right like the storage list

browser/lib/Languages.js, browser/lib/i18n.js, browser/main/Main.js, browser/main/modals/PreferencesModal/UiTab.js
This PR centralized all languages into 1 file so that next time you want to add a new language just add it to the Languages.js file.
=> Centralized languages into 1 files

browser/main/lib/dataApi/moveNote.js
Fixes #1788
How it works:
Moving note from one folder to another folder at the same storage -> don't touch the images
Moving note from one folder to another folder at different storages -> copy the images to the new storage, delete the images from the old storage
Limits: 
If the same image is referenced in multiple notes at the old storage, moving only one note (with the image) will result in deleting the image at the old storage. But this is another bug.
=> Fixed moving notes with images

browser/components/TagListItem.js, browser/components/TagListItem.styl, browser/main/NoteList/index.js, browser/main/SideNav/index.js, browser/main/index.js, browser/main/modals/PreferencesModal/UiTab.js, tests/components/__snapshots__/TagListItem.snapshot.test.js.snap
When a tag is selected, the tag list narrows to show only the related
ones: all tags associated to the currently visible notes. Clicking on
the plus sign near another tag narrows the list again to the tags of
notes associated with the firstly AND secondly selected tag. To show
every tags again, press the tag icon on the top-left corner of
Boostnote.
Before:
After:
NOTE: Tags are joined with `&` character (`#` not works) in
`location.pathname` thus it will make the tags with this character
unavailable. Any suggestion to pass multiple values via pathname?
Please check *browser/components/TagListItem.styl*, I'm sure that it can be simpler.
* https://github.com/BoostIO/Boostnote/issues/1756
=> Show only related tags, select multiple tags

.eslintrc, .travis.yml, browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js, browser/components/MarkdownSplitEditor.js, browser/main/lib/dataApi/attachmentManagement.js, browser/main/lib/dataApi/exportNote.js, tests/components/__snapshots__/TagListItem.snapshot.test.js.snap, tests/dataApi/attachmentManagement.test.js
Fixes #1827
New Pullrequest because @Rokt33r  asked me to do so due to a modified master branch
=> Issue 1827

browser/main/NoteList/index.js
fix #1869 
I found one more bug during investigation of this issue. 
When the dragged note is not the focused note(s), the focused note(s) are moved to the target folder, but the dragged note is still in the same folder. 
[this commit](https://github.com/BoostIO/Boostnote/commit/2d0f7589eaa1c6ecc47624fcb67ac30a6589c887) handles this issue.
=> fix drag drop more than one note bug

browser/components/markdown.styl
font color in code block unusual when preview markdown
[kazup01 fix same bug on 24 Sep 2017](https://github.com/BoostIO/Boostnote/commit/ec8fac11993aa4308111a47a481bc7ee35901e72#diff-a54dec67725b3e604a34d39a7fcb72f6)
[but bring in same bug on 4 Oct 2017](https://github.com/BoostIO/Boostnote/commit/d8e19d9c17611efced990255e35a69242e15df58#diff-8ea283d669e20ef48dfcd6839e92c02a)
=> Fix font color in code block(markdown preview)

browser/components/CodeEditor.js, browser/components/MarkdownPreview.js, browser/lib/convertModeName.js, browser/main/Detail/SnippetNoteDetail.js, lib/main.html
fix #1909 
Embedded js uses combined mode. multiplex.js handles this combined mode.
=> Codemirror multiplex support

browser/components/NoteItemSimple.styl
Noticed a weird styling issue with note items when they are toggled to "simple", edges became white and hovering over a note item wasn't distinct enough. This pr fixes that for all the dark themes (Dark, Solarized Dark & Monokai). Can't wait for v0.11.5! 💪 
The issue:
New and improved:
=> fixed NoteItemSimple styling for the dark themes

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js
`this.isMovingNote` is always undefined, so this code would not detect when the note is moving, and prevent against undesirable behaviour.
These alerts were found using lgtm.com:
https://lgtm.com/projects/g/BoostIO/Boostnote/alerts
------
Full disclosure, I work for Semmle on lgtm.com
=> Fix mis-referenced state properties

browser/components/SnippetTab.js, browser/main/Detail/SnippetNoteDetail.js
Executions of `setState()` may be batched, and so updates to `this.state` and
`this.props` can be asynchronous, so references to `this.state` and `this.props`
should not be made in the new state, and instead the callback form of
`setState()` should be used.
These alerts were found using lgtm.com:
https://lgtm.com/projects/g/BoostIO/Boostnote/alerts/?mode=tree&ruleFocus=1819283066
see: https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous
------
Full disclosure, I work for Semmle on lgtm.com
=> fix inconsistent updates to react component state

package.json
This is to fix second point of my comment of [issue#1003](https://github.com/BoostIO/Boostnote/issues/1003)
CodeMirror released new version which fixed this issue.
=> Fix #1003 Update CodeMirror version

browser/lib/utils.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Main.js, browser/main/index.js, browser/main/lib/ConfigManager.js, browser/main/lib/shortcut.js, browser/main/lib/shortcutManager.js, browser/main/modals/PreferencesModal/HotkeyTab.js, package.json, yarn.lock
This feature has been requested here: https://github.com/BoostIo/Boostnote/issues/1699
This is the feature to allow user to toggle editor mode using a keyboard shortcut.
The default shortcut for toggling editor mode is `ctrl+m`. But user can still customize this at the hotkeys section in setting.
I have also added a shortcut manager, so if you want to create another shortcut in your next feature, just add it to the `browser/main/lib/shortcut.js` file like this:
```
'<nameOfTheFunction>' : () => { <function content> }
```
Then add your shortcut to the `hotkey` property in `DEFAULT_CONFIG` in `browser/main/lib/ConfigManager.js` file.
Remember the `<nameOfTheFunction>` that you added earlier must be the same as the `<nameOfTheFunction>` in the ConfigManager file.
For example here is my …
=> Shortcut to toggle mode

browser/main/Detail/TagSelect.js
When a tag  is deleted from a note, the taglist did not updated: the deleted tag was still in the list. If the
tag was created in the current session, it was removed, worked as expected.
The reason is: until the note is not updated, the tag list is not
initialized for first in the "delete tag button" handler, but it works
in the second case. Tried out using backspace to delete the tag, it
works.
Before:
After:
=> Refresh taglist to remove unused tags on deleting

browser/main/store.js
I'm not sure, but the original logic seemed buggy to me: the `uniqueKey` was not added to the state (see the patch).
=> Refactoring of store.js

browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js, browser/components/MarkdownSplitEditor.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js
With this feature, users can now customize how the markdown should look like. More info: https://issuehunt.io/repos/53266139/issues/184
Here is how it looks
As you can see, the user can choose to use custom css or not by clicking on the allow custom css checkbox in the preview section and then specify the custom css in the code editor bellow.
By default the custom css is disabled.
If the user export the note as html, their custom style will be applied too.
=> Added custom markdown css

browser/components/MarkdownPreview.js
In #1944, I didn't care about local file link. Before #1944, local file is opened by shell. This PR supports the local file link again. In #2003, we discussed about custom url scheme. This implementation doesn't check the url before opening by shell, so actually it can handle the custom url. 
When I think about security, this implementation seems bit dangerous, but we can see the same behaviour before. 
@Rokt33r
=> open local file by shell

lib/main-menu.js
The zoom in & zoom out window feature has been requested here: https://github.com/BoostIo/Boostnote/issues/1907
Now, users can zoom in and zoom out the boostnote window using `ctrl + '+'` and `ctrl + '-'`, respectively.
I have tested this feature on linux mint, I think it'll work on window too (I'm not very sure) and I haven't tested on mac (for obvious reason, I'm poor and can't afford a macbook :smile: )
=> added zoom in & zoom out window feature

browser/lib/consts.js
@ZeroX-DG It seems using `appData` doesn't work on some other OSs(including macOS). So I think that's the reason why you couldn't repopulate this bug.
=> Fix wrong path of snippets.json

locales/en.json
It seems that contains two `Select Folder` key with same value.
I think it is unnecessary.
=> Fix en.json

browser/components/NoteItemSimple.styl
This was bugging me so I fixed it :)
Before:
After:
=> [Dark Theme]: Fixes the text color for an active note with an empty title

browser/components/markdown.styl
Fixed [[kdb]] **background-color** to **themeDarkBackground** in monokai theme
=> Fixed Keyboard tag unvisible in monokai theme[#1945]

browser/components/CodeEditor.js, browser/components/MarkdownSplitEditor.js, browser/components/MarkdownSplitEditor.styl
You can now dragging the border between Editor & Preview to left/right
=> Add new future resize editor & Preview Panes by dragging.(#1977)

browser/main/Detail/InfoPanel.styl
Fix for https://github.com/BoostIO/Boostnote/issues/2043
=> Fixed info panel positioning

browser/main/Detail/MarkdownNoteDetail.js, browser/main/lib/ConfigManager.js, browser/main/lib/shortcutManager.js
related: #2101 
In editor mode, pressing M key trigger editor mode toggle(Preview <=> Split)
1. change wrong default value
2. But **those who already set hot key as 'Cmd + M' should change 'Command + M' manually**  (Because Boostnote use localStorage to save user configuration including hotkey. But It can only be changed by user)
3. change `Command + M` action to more desirable way(I make it focus after change editor mode so that It sustains focus when editing)
=> Fix MacOs 'M' key issue

browser/main/lib/ConfigManager.js
This and #2109 fix #2101, fix, fix #2098, fix #2094, and fix #2086.
=> Rewrite invalid hotkeys when loading

browser/components/MarkdownPreview.js, browser/components/markdown.styl, package.json, yarn.lock
=> Fix rendering of admonitions in Windows

browser/main/SideNav/StorageItem.js, browser/main/lib/dataApi/addStorage.js, browser/main/lib/dataApi/index.js, browser/main/lib/dataApi/resolveStorageData.js, browser/main/lib/dataApi/toggleStorage.js, browser/main/store.js, tests/dataApi/toggleStorage-test.js
The root cause of this issue is that when the folder is clicked,
the router pushed the path and the StorageItem component has been
refreshed and isOpen has been reset
- Add storing collapse state for storage
- Add tests
- Default as collapsed for fallback
fix BoostIo/Boostnote#1979 BoostIo/Boostnote#1911
=> Add collapsed state for storage

browser/components/CodeEditor.js, browser/lib/consts.js, browser/lib/normalizeEditorFontFamily.js, browser/main/modals/PreferencesModal/UiTab.js, tests/lib/normalize-editor-font-family-test.js
=> Improve uitab editor

browser/components/MarkdownPreview.js, browser/main/global.styl
The disappearing scroll bar bug is extremely annoying and has been reported here: https://issuehunt.io/repos/53266139/issues/1632
After working on my personal project, I have found a fix for this issue.
This is bug exists due to the style of the scroll bar of codemirror, instead of applying for just codemirror, it applied to the whole window, everything that has its scroll bar unstyled. So the solution is to override that style!
=> fixed disappearing scroll bar

browser/components/CodeEditor.js, browser/main/modals/PreferencesModal/SnippetEditor.js
Fixes #1428.
Improves bracket editing by autoclosing markdown patterns for: LaTeX, italic, bold, code snippets, and Python docstrings.
Added pairs:
- `$$` (latex)
- `**` (markdown italic and bold)
Added triplets:
- ` ``` ` (code snippets)
- `"""` and `'''` (python docstrings)
=> Improve bracket autoclosing

lib/main-menu.js
**Why**
Now shortcut key for **Next Note**(<kbd>ctrl+J</kbd>) and **Previous Note**(<kbd>ctrl+k</kbd>)had been conflicted with **Emac** Key map setting or **sublime** or **vim**, one of these key map settings also had It's inner use of key.   like **Emac** using  <kbd>ctrl+k</kbd> for repeatedly to kill multiple lines, but **sublime** using <kbd>ctrl+k</kbd> for combine action key. 
also see #2133 
**Do**
as above said, we need to change key map binding for 'Next Note' and 'Previous Note', I suggested that using <kbd>CommandOrCtrl+]</kbd> for 'Next Note', <kbd>CommandOrCtrl+[</kbd> for 'Previous Note'.
please review.
=> Replace shortcut for 'Next Note' and 'Previous Note'

browser/main/Detail/index.js
Solved #2156 
This bug appeared due to the fact that in 'Detail' component the current note was searched in a chunk of Redux store in which all of a user's notes are stored. Not defined by the selected tab. Both trashed and not. This problem was solved by different searching the current note for each particular case: homepage, trashed and starred items, input and tag searching. In this way, a removed or restored note is checked for being trashed now.
=> Issue 2156

browser/main/modals/NewNoteModal.js
Hello!
First of all, thanks for the great product. 👏 
Issue is when you create a new note you still see previous note for a sometime. The cause of issue is that re-rendering of code-editor happens after closing create-a-note section. I've added a small timeout to avoid it. 
Before: 
After fix:
=> Flickering on create note

browser/components/MarkdownPreview.js, browser/components/render/MermaidRender.js, browser/lib/markdown.js, package.json, yarn.lock
Support all [mermaid](http://knsv.github.io/mermaid) charts.
#389
For example: 
```
```mermaid
sequenceDiagram
loop every day
Alice->>John: Hello John, how are you?
John-->>Alice: Great!
end
```
=> Add mermaid support

browser/main/TopBar/index.js
Use 'select' instead of 'setSelectionRange' to avoid not focused when search input element has text in it. 
Fixed #2018
=> Fixed 'Focus Search' shortcut

browser/main/Detail/FullscreenButton.js, lib/main-menu.js
Add hotkey for toggle side bar
> <kbd>Command+B</kbd> for macos
> <kbd>Ctrl+B</kbd> for others
The **B** abbreviation for 'Side  **B**ar'.
#2165
=> Hotkey for toggle editor fullscreen

browser/components/MarkdownPreview.js, browser/main/lib/dataApi/attachmentManagement.js, tests/dataApi/attachmentManagement.test.js
Proposal for fixing #2139.
The main idea is to:
- Allow either / or \ as part of the :storage paths in the markdown content. That way we preserve compatibility with already created documents.
- Adjust RegExp in the code to handle this and then sanitize to use OS dependent path separator. This allow us to show images in win and *nix platforms without touching the markdown content (very useful if you version your notes in 3rd party storage like Dropbox)
- As a consequence of these changes, no deletion of attachments will happen when opening the note between win and *nix.
- It would be very nice to open a PR for making the "deletion of attachments" feature configurable.
=> Fix attachment interoperability between win and *nix

browser/components/MarkdownPreview.js
Fixed issue: #2159
The path generated by `file-url` begins with `file:///`.
```javascript
file.replace('file://', '')  //    /C:/Users/........  wrong path.
file.replace('file:///', '') //    C:/Users/........   correct path.
```
=> Fix search value for html export path

browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/TagSelect.js, lib/main-menu.js
Add shortcuts for focusing tag editor. Also see #2132 
Because <kbd>Control+T</kbd> is used for create new snippet.
So use:
<kbd>Command+Shift+T</kbd> for MacOSX
<kbd>Control+Shift+T</kbd> for others.
Please review.
=> New Feature: Shortcuts for focusing tag editor(CmdOrControl+Shift+T)(#2132)

browser/lib/search.js
This change adds the content of code snippets to the scope of search. The highlighting and all current search functionality works as expected.
=> Add code snippets to search scope

browser/components/MarkdownPreview.js, browser/components/render/MermaidRender.js
Fix for https://github.com/BoostIO/Boostnote/issues/2215
Mermaid theme will change depending on whether the overall theme is light or dark.
=> Mermaid dark theme rendering fix

browser/main/lib/dataApi/attachmentManagement.js
Fix for issue https://github.com/BoostIo/Boostnote/issues/2088.
In specific situation, when all below conditions are met :
- one of the snippets notes tabs is a Markdown tab,
- the migrateAttachments code is called on a snippet note,
- historical attachments location '/images' exists in snippet storage folder
Following exception is being thrown :
> path.js:28 Uncaught TypeError: Path must be a string. Received undefined
at assertPath (path.js:28:11)
at Object.join (path.js:1251:7)
at createAttachmentDestinationFolder (<anonymous>:84:25)
at Object.migrateAttachments (<anonymous>:101:7)
at MarkdownPreview.rewriteIframe (<anonymous>:512:28)
at MarkdownPreview.proxiedMethod (<anonymous>:44:30)
at MarkdownPreview.componentDidUpdate (<anonymous>:420:54)
at MarkdownPreview.proxiedMethod …
=> Fix for issue #2088 :  snippet notes are not displaying in markdown 

lib/main-window.js
This change allows the window to be restored at the same position as when it was closed.
=> restore window position

.boostnoterc.sample, browser/main/NoteList/index.js, browser/main/lib/ConfigManager.js, tests/lib/rc-parser-test.js
- save sort configuration in `config.[folderKey].sortBy`
- use lodash ` _.get(config, [folderKey, 'sortBy'])` to avoid error
#fixes #933
=> Add per-folder sort

package.json, yarn.lock
This change updates to the newest version of Electron.
It also fix the error `Error: Cannot find module 'electron-gh-releases'` when packaging with npm-v5.
=> update electron version

.editorconfig
This change adds basic EditorConfig file.
=> add EditorConfig

browser/main/Detail/SnippetNoteDetail.js, browser/main/NewNoteButton/index.js, browser/main/modals/NewNoteModal.js, browser/main/modals/PreferencesModal/ConfigTab.styl, browser/main/modals/PreferencesModal/UiTab.js, locales/en.json, locales/fr.json
The change adds the option to define the default language of a new snippet code.
It should resolve #2349.
=> add default language for snippet note

browser/styles/index.styl
Was about to start another issue and noticed this. It really bugged me so I fixed it 😄This also stops the scrollbar from covering the status bar. If can't see the issue check the bottom right corner of the screenshots.
BEFORE:
AFTER:
=> Statusbar height fix

browser/main/SideNav/index.js
This change is fixing the bug #2321 due to the unescaped characters `#` or `?` in the route.
=> fixing bug #2321 

browser/lib/markdown-toc-generator.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, lib/main-menu.js, package.json, tests/helpers/setup-browser-env.js, tests/lib/markdown-toc-generator-test.js, webpack-skeleton.js
This PR aims to solve #1436.
- Adds table of contents for any currently displayed Markdown note or Markdown snippet, at current cursor position.
- Consequent generations update existing TOC.
- Generated TOC is case sensitive to handle #2067
**Shortcut** : _SHIFT+CTRL+T_
**Menu** : _File / Generate/Update Markdown TOC_
=> Automatic table of contents generation for Markdown

contributing.md
Improved some of the grammar mistakes and wording of the English portion. There are still a few things that are hard to understand.
=> Clarify contributing.md

browser/components/CodeEditor.js, yarn.lock
This change fixes the input position of the editor when going fullscreen or resizing the splitEditor.
It should close #2397.
=> fix input position when going fullscreen or resizing splitEditor

browser/main/Main.js, browser/main/modals/PreferencesModal/StoragesTab.js, locales/da.json, locales/de.json, locales/en.json, locales/es-ES.json, locales/fa.json, locales/fr.json, locales/hu.json, locales/it.json, locales/ja.json, locales/ko.json, locales/no.json, locales/pl.json, locales/pt-BR.json, locales/pt-PT.json, locales/ru.json, locales/sq.json, locales/tr.json, locales/zh-CN.json, locales/zh-TW.json
Change the header "Storages" to "Storage Locations" in English.
This is more consistent with the "Add Storage Location" button and makes more sense in English. Happy to hear feedback!
=> change storage header from Storages to Storage Locations

browser/main/modals/PreferencesModal/FolderItem.styl, browser/main/modals/PreferencesModal/StorageItem.styl
=> Add text-overflow: ellipsis to FolderItem

browser/main/modals/PreferencesModal/HotkeyTab.js, browser/main/modals/PreferencesModal/UiTab.js, locales/da.json, locales/de.json, locales/en.json, locales/es-ES.json, locales/fa.json, locales/fr.json, locales/hu.json, locales/it.json, locales/ja.json, locales/ko.json, locales/no.json, locales/pl.json, locales/pt-BR.json, locales/pt-PT.json, locales/ru.json, locales/sq.json, locales/tr.json, locales/zh-CN.json, locales/zh-TW.json, yarn.lock
All of the other options are in Title Case so it makes sense to
change this option's label to Title Case as well.
=> Capitalize settings labels

browser/main/lib/ConfigManager.js
By default the Toggle Editor Mode hotkey was set to Command + M,
which is a great and mnemonic hotkey. Unfortunately that hotkey
is also the hotkey to minimize an application.
This commit changes the default Toggle Editor Mode hotkey to
Command + Option + M on OS X, which will not minimize the window
and maintains the mnemonic pattern.
=> Change Toggle Editor Mode hotkey on OS X

browser/components/NoteItem.js
Notes inside My Storage did not display timestamp of last edit,
this commit makes the timestamp consistent across all notes in
all locations.
Before:
After:
=> Display timestamp on all notes

browser/components/NoteItem.styl, browser/components/NoteItemSimple.styl, browser/components/TodoListPercentage.styl, browser/main/Detail/TagSelect.styl, browser/main/Detail/ToggleModeButton.styl, browser/styles/index.styl
Updated the Monokai theme to fix a few styling bugs and updated the styling of the NoteItem, NoteItemSimple, toggleModeButton and the TodoListPercentage to follow the logic of the new Dracula theme.
=> Monokai theme fixes

browser/main/lib/dataApi/attachmentManagement.js
Fix drag-drop image rotate wrong, as Jordan Thornquest mentioned in slack
=> Fix drop image rotate wrong

browser/components/MarkdownEditor.styl
This change fixes hidden the note's infos or the tag autocomplete behind the note's preview.
It's fixing #2472
=> fix visual bug with preview

browser/main/global.styl, browser/main/modals/PreferencesModal/SnippetList.js
This change fixes small graphical bugs in the snippet list
Before: ![screenshot](https://user-images.githubusercontent.com/587742/46262876-02ab6f80-c508-11e8-8198-282d0ecce6cd.jpg)
After: ![screenshot](https://user-images.githubusercontent.com/587742/46262877-0dfe9b00-c508-11e8-827e-3c7a0a12b8f2.jpg)
=> fix graphical bugs in snippet list

browser/main/modals/PreferencesModal/SnippetTab.js
This commit protects from a TypeError that is consistently
thrown on the Snippets page.
=> Fix TypeError thrown on the Snippets page

extra_scripts/codemirror/mode/bfm/bfm.css, extra_scripts/codemirror/mode/bfm/bfm.js, gruntfile.js
This change fixes several bugs:
- reset row index on blank line
- separate even rows' colors for Solarized Dark and Solarized Light themes
Before:
After:
#2505
[x] Bug fix (Change that fixed an issue)
[ ] Breaking change (Change that can cause existing functionality to change)
[ ] Improvement (Change that improves the code. Maybe performance or development improvement)
[ ] Feature (Change that adds new functionality)
[ ] Documentation change (Change that modifies documentation. Maybe typo fixes)
[x] My code follows the project code style
[ ] I have written test for my code and it has been tested
[x] All existing tests have been passed
[x] I have attached a screenshot/video to visualize my change if possible
=> fix color for even rows in table

browser/components/MarkdownEditor.js, browser/components/MarkdownSplitEditor.js, browser/components/TodoListPercentage.js, browser/components/TodoListPercentage.styl, browser/main/Detail/MarkdownNoteDetail.js
This change adds button un-check all checkboxes (issue #975)
=> Add button clear all checkboxes

browser/lib/findNoteTitle.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js, tests/lib/find-title-test.js
Builds on front matter changes introduced by #2347
=> Title will now be extracted from front matter if title: is present.

extra_scripts/codemirror/addon/hyperlink/hyperlink.js
This change disables the following popover on attached images:
=> disable hyperlink for attachments

browser/components/TagListItem.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Main.js, browser/main/SideNav/index.js, tests/components/__snapshots__/TagListItem.snapshot.test.js.snap
This change adds the possibility to delete a tag through its context menu.
=> delete tag through context menu

browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js, browser/components/MarkdownSplitEditor.js, browser/lib/markdown.js
This changes fixes the error generated by toggling the split editor.
=> fix error generated by toggling split editor

browser/components/StorageList.js
There was a typo with both the prop name (in the propTypes check) and the styleName for storageList-empty.  This prevented the "No storage mount." div from ever being displayed (see the before and after screenshots attached).
Before:
After:
=> fix: Fixed storageList typo (storgaeList).

browser/components/MarkdownPreview.js
When saving as HTML, the raw text was being HTML escaped prior to
running it through markdown. This was preventing blockquotes from
rendering because greater-than signs were escaped. The HTML escaping
seems unneeded since the markdown renderer already takes care of it,
and it also wasn't consistent with how markdown was being rendered
within the application.
Fixes #1922
Fixes #2514
=> Fixed "Save as HTML" to respect blockquotes.

dev-scripts/dev.js, lib/main-window.js, package.json
This is fix :bug: 
ERRROR : [1] 7816 segmentation fault (core dumped) in Ubuntu 18.10 and i think all linux distro with glibc 2.28
[Issue](https://github.com/BoostIO/Boostnote/issues/2483)
=> fix segmentation fault with glibc 2.28

browser/main/lib/ConfigManager.js
I created this bug in #2435. This should fix it.
=> Fix bug caused by poor regex

.vscode/launch.json, .vscode/tasks.json, docs/debug.md, package.json, webpack.config.js
1. First run **watch** task.  **Terminal->Run Build Task…** chose **Build Boostnote** task. Or you can run `yarn run watch` command in terminal.
2. Now you can debug use **F5**
=> Add vscode debug support

browser/main/SideNav/index.js
empty trash requires user confirmation. This is mandatory as it is a destructive operation.
=> enhancement for #2588

browser/components/CodeEditor.js
This change fixes the cursor position after a snippet have been expanded.
- #2082
=> fix cursor position after expending snippet

browser/main/Main.js
Fixes #1406 
Hey friends, this fix is borrowed from a CodeMirror issue: https://github.com/codemirror/CodeMirror/issues/5321#issuecomment-375232302
It's a one-liner that should be run only once. I wasn't sure where to put this code so I tried a main entry that is executed once: the mounting of the main window.
**If you think of a better place to put this please let me know so I can fix**. I'm not familiar too much with boostnote code.
=> Remove emacs keymap Ctrl-V binding to allow pasting

package.json
On Ubuntu 18.10 there is a issue with glibc versions below 2.28 see
[Prebuilt Electron binaries segfault at startup on Arch Linux with glibc 2.28 #13972](https://github.com/electron/electron/issues/13972)
=> Update electron framework to version 3.0.8

PULL_REQUEST_TEMPLATE.md, contributing.md, docs/code_style.md
This PR added a pull request template and update docs to keep it up to date
https://github.com/BoostIO/Boostnote/issues/2528
- :white_circle: My code follows the project code style
=> Added PR Template and update docs

browser/components/MarkdownPreview.js
User can now go back to 'preview' from 'editor with preview' on right click when the 'Switch to Preview' preference is set to 'On Right Click'
#2199
=> Ability to go from 'editor with preview' mode to 'preview' using mouse

browser/main/StatusBar/StatusBar.styl
fix white text not visible on white background for default theme and white theme.
@ZeroX-DG this is same as #2583. I am sorry for the confusion.
=> fix GUI style element for default theme

browser/main/StatusBar/index.js, lib/main-menu.js
- Updated the zoom logic for the zoom in/out menu items so that if you zoom it reflects in the status bar and the config. 
- Also added an actual size / zoom reset menu item for convenience.
The shortcuts follow the standard controls I have seen in popular apps like google chrome or spotify.
You may notice that I have bound the zoom in to `CommandOrControl+=` instead of the standard `CommandOrControl+Plus`, this is due to an electron bug. I have posted a comment here. Feel free to check it out https://github.com/electron/electron/issues/6731. The accelerator does the same thing so it has no effect on user experience.
I've tested everything on macOS and it seems to be fine 👍
I need others to test on windows and linux please 🙏 
https://github.com/BoostIO/Boostnote/issues/2554 …
=> Zoom Controls

browser/main/NoteList/index.js
This ensures that the newly created note is visible and selected in the note list.
Fixes #2241
=> Clear search when a new note is created

browser/main/Detail/InfoPanel.js, browser/main/Detail/InfoPanelTrashed.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/NoteList/index.js, lib/main-menu.js
This PR only fixes the bug reported in #2026, as it doesn't implement any new feature (like printing snippets).  
Now, when trying to print a snippet from the InfoPanel, it will show the same warning as when trying to print it from File->Print (instead of just showing an error in the console).
#2026 
- :radio_button: : Bug fix (Change that fixed an issue)
- :radio_button: : My code follows [the project code style](docs/code_style.md)
- …
=> Warning when printing snippet

browser/main/NoteList/index.js, lib/main-menu.js
This pr initially started as adding `Clone Note` to the menu bar and having a keyboard shortcut for it. However once I got started I thought that the menu items needed some restructuring and some of the keyboard shortcuts needed to be more platform friendly (i.e. using Command on macOS vs Control on Windows\Linux). Some of the keyboard shortcut changes are listed below. 
Focus Note: On macOS its now `Command+E` otherwise it remains `Ctrl+E`
Clone Note: On macOS its `Command+D` otherwise it is `Ctrl+D`
I made an attempt on bringing back the `Delete` key for non macOS machines but you can't have multiple accelerators on the same menuItem and I was too lazy to code it elsewhere 🤷‍♂️  I have also removed the `Ctrl+D` shortcut for deleting a note since the global shortcut is different as of …
=> Menu items overhaul

browser/main/lib/dataApi/copyFile.js, tests/dataApi/copyFile-test.js
Currently, Boostnote seems managing file path with encodeURI. 
so if your path contains unicode character, it turns encoded URI. 
`ex) 'User/안녕/dev', ->'User%2F%EC%95%88%EB%85%95%2Fdev`
I cannot figure out which process handle path encoding,
but it affected `copyFile` only. so I attached `decodeURI` here.
#2578
- …
=> Handle encoded uri path on `copyFile`

browser/main/SideNav/StorageItem.js
Changes the highlighting to more noticeable when  a note is dragged over a folder.
#1885 
- :radio_button:  Improvement (Change that improves the code. Maybe performance or development improvement)
=> Dragged note highlighting

.vscode/launch.json
Fixed typo that prevented debugging on windows operating systems.
[#2726](https://github.com/BoostIO/Boostnote/issues/2726)
- :white_circle: I have attached a screenshot/video to visualize …
=> Fixed windows debug path

browser/components/markdown.styl
I fixed the position of the checkbox shifted to the right.
I diverted the value of `margin-left` from the following code in line 77 of `browser/components/markdown.styl`.
```
li
label.taskListItem
margin-left -1.8em
```
```
- Normal UL
- test
- Normal UL
- test
> Quote in list element
- text2
> Normal Quote
> Quote in checkbox
- test
- test
```
#2729 
- :radio_button: My code follows [the …
=> fixed issue #2729

browser/components/CodeEditor.js, browser/components/MarkdownEditor.js, browser/components/MarkdownSplitEditor.js, browser/lib/newNote.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/Main.js, browser/main/NoteList/index.js, browser/main/lib/dataApi/createNote.js, browser/main/lib/dataApi/createSnippet.js, browser/main/lib/dataApi/migrateFromV5Storage.js, browser/main/lib/dataApi/updateNote.js, browser/main/lib/dataApi/updateSnippet.js, tests/dataApi/createNote-test.js, tests/dataApi/createSnippet-test.js, tests/dataApi/updateNote-test.js
This PR solves the #2469 issue, it allows the user to highlight lines of code within a snippet of code by clicking on the line number. This highlight is not temporary, it persists when exiting Boostnote. Used CodeMirror built-in functionality to do this.
To use this feature you just need to click the line number of the respective line you want to highlight.
Issue #2469 Line highlighting within code block
- :white_circle: : Breaking change (Change that can cause existing functionality to change)
- :white_circle: Documentation change (Change that modifies documentation. …
=> Feature - Line highlighting within code block #2469

browser/components/markdown.styl
Solves #2557 by allowing wrapping only for inline math (reverts 36e63bb8a9021ad05933f215638215aebd4d9afb). Straightforward solution.
Issue #2557 
- :radio_button: Breaking change (Change that can cause existing functionality to change)
- :radio_button: I have attached a …
=> Fix issue 2557 katex alignment in display math

browser/components/CodeEditor.js
https://github.com/BoostIO/Boostnote/pull/2466
=> Fix Cmd+Left to go to end of line on Mac

browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js
In preview mode, when dropping an image, the Editor is shown and the image in added at the end of the file on a new line.
- #817
- :white_circle: I have attached a screenshot/video to …
=> drag image into preview

browser/components/CodeEditor.js, browser/main/modals/PreferencesModal/HotkeyTab.js, browser/main/modals/PreferencesModal/UiTab.js
This change fixes the editor so `Ctrl+V` or `Cmd+V` can paste an image.
- #2716
- #2719
- #2736
=> fix paste image

browser/main/Detail/TagSelect.js
`saveTagsAlphabetically` feature has been added in 8b4a9dd, but this feature removed by 4e80e1d. Both commits are in same PR #2314.
If this feature was valid, tags of a note would be saved in alphabetical order. However, in the latest version, the tags are saved in order of creation as below.
Now, I fix this feature and the tags are saved in alphabetical order as below.
- #2699 
- …
=> Fix feature 'saveTagsAlphabetically'

browser/components/CodeEditor.js, browser/lib/newNote.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/modals/PreferencesModal/UiTab.js, package.json
for #2351 
add new feature: auto detect snippet language
try to detect after pasting and mode has not been set
- ⚪️ : I have written test for my code and it has been tested
=> new feature: auto detect snippet language

docs/build.md, docs/de/build.md, docs/de/debug.md, docs/debug.md, docs/fr/build.md, docs/pt_BR/build.md, docs/pt_BR/debug.md, docs/zh_TW/build.md
This PR bring to us the Brazilian Portuguese translation.
- :radio_button: It's documentation, so the checklist items does not fit well to this scenario.
=> Pt br translations

locales/pt-BR.json
There was a misspelling on the word "escluir", the correct one is "excluir", as you can see on [google translate](https://translate.google.com/?source=osdd#view=home&op=translate&sl=pt&tl=en&text=excluir)
- :white_circle: All existing tests …
=> typo on pt-BR.json

browser/main/Detail/SnippetNoteDetail.js
For #2769.
Replace current fullscreen button of SnippetNote to [FullscreenButton](https://github.com/BoostIO/Boostnote/blob/master/browser/main/Detail/FullscreenButton.js) in reference to [MarkdownNoteDetail](https://github.com/BoostIO/Boostnote/blob/master/browser/main/Detail/MarkdownNoteDetail.js#L466).
**Before**
**After**
#2769 
- :radio_button: My code follows [the project code …
=> Replace current fullscreen button of SnippetNote to FullscreenButton module

browser/main/Detail/TagSelect.styl, browser/styles/Detail/TagSelect.styl
When the number of tags exceed the width of the window, scroll bar is not showing.
#2688 
=> show the scroll bar when the tag list is overflow

docs/build.md
Added section to build.md with instructions to check out PRs
-  :radio_button: Documentation change (Change that modifies documentation. Maybe typo fixes)
=> Updated build.md to include directions for checking out PRs

lib/main-menu.js
Adds an option under the Help menu to open various syntax cheatsheets in a browser window. 
- ✔️  Improvement (Change that improves the code. Maybe performance or development improvement)
-✔️ Feature (Change that adds new functionality)
- ✔️ My code follows [the project code style](docs/code_style.md)
-✔️ All existing tests have been passed
-✔️ I have attached a screenshot/video to visualize my change if possible
=> Added cheatsheets to menu

browser/main/lib/dataApi/init.js
Filters storages on init to filter out locations that not longer exist. Previously it would attempt to make a folder on whatever paths were there which would raise an exception if the drive was not connected. 
User will need to restart Boostnote with the drive reinserted to access storage, but it will show up automatically on restart.
Cause was attempting to access a folder that does not exist, and also attempting to write a boostnote.json inside if there was not one already. This behaviour is fine on a local disk but not a missing external drive. 
fix #2799
Fix #2711 
- ✔️ Bug fix (Change that fixed an issue)
- ✔️  Improvement (Change that improves the code. Maybe performance or development …
=> Removal of USB drive will no longer cause irreparable damage.

extra_scripts/boost/boostNewLineIndentContinueMarkdownList.js
Fix the problem where the user update the numbered to the middle of the list, the following number(s) did not updated.
Screenshot:
#2170 
- :radio_button: I have attached a screenshot/video …
=> Fix the auto-updating numbered list to the middle of a list

browser/main/lib/ConfigManager.js
It makes possible to use Cmd as abbreviation for setting as hot key.
#2194 
- :black_circle: Bug fix (Change that fixed an issue)
- :black_circle: My code follows [the project code style](docs/code_style.md)
=> #2194 - fixes Hotkey not working

lib/main-app.js, package.json
App will no longer attempt to update whilst in development mode.
Follows guidelines from https://electronjs.org/docs/tutorial/updates
=> Disable updates in dev

browser/main/NoteList/index.js
This PR fixed the unwanted behavior when users delete a note. Instead of showing the create note message, the next note in the list will be displayed.
**Before**
**After**
https://github.com/BoostIO/Boostnote/issues/2615, https://github.com/BoostIO/Boostnote/issues/2343
- :white_circle: I have written test for my …
=> Fixed delete note not navigating to the next note

browser/main/lib/ConfigManager.js
I received [this suggestion](https://github.com/BoostIO/Boostnote/pull/2748#issuecomment-456680112) and changed default editor font of Windows and macOS.
#1995 
- :radio_button: I have …
=> Change default editor font #1995

browser/components/MarkdownPreview.js, browser/components/markdown.styl
I added a new feature like [the Medium Image Zoom feature](https://medium.design/image-zoom-on-medium-24d146fc0c20).
#1448 
- :radio_button: I have attached a screenshot/video to visualize …
=> Zoom in and out image #1448

browser/components/CodeEditor.js, browser/main/lib/dataApi/attachmentManagement.js, tests/dataApi/attachmentManagement.test.js
This change is base on the work of @ehhc (PR #2835).
The difference is that it won't break the gallery feature and improve a test to correctly assert all image paths are correctly generated.
- #2834
- :radio_button: All existing tests have …
=> fix image path due to bad regex

browser/main/modals/PreferencesModal/Crowdfunding.js
Fixed grammar error in notes.  #2844 
Changed a sentence from `We think developers who has skill and did great things must be rewarded properly.` to `We think developers who have skills and do great things must be rewarded properly.`
- :radio_button:: Documentation change (Change that modifies documentation. Maybe typo fixes)
- …
=> [Fix  #2844] Grammar Error In Notes

browser/main/NoteList/index.js
Cloning a note will now copy the missing following note properties to the new note
* `description`
* `snippets`
* `tags`
* `isStarred`
I'm adding the properties tags and `isStarred` also to this PR because I'm sure after clone a note with tag they should also be on the new note.
#2859 Cloning of snippets doesn't work (win 10)
- :large_blue_circle: My code follows [the project code …
=> [Fix] Cloning a note will now clone more note properties

browser/components/MarkdownPreview.js, browser/main/Detail/InfoPanel.js, browser/main/Detail/InfoPanel.styl, browser/main/Detail/InfoPanelTrashed.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/NoteList/index.js, browser/main/lib/dataApi/exportFolder.js, browser/main/lib/dataApi/exportNote.js, lib/main-menu.js, locales/da.json, locales/de.json, locales/en.json, locales/es-ES.json, locales/fa.json, locales/fr.json, locales/hu.json, locales/it.json, locales/ja.json, locales/ko.json, locales/no.json, locales/pl.json, locales/pt-BR.json, locales/pt-PT.json, locales/ru.json, locales/sq.json, locales/th.json, locales/tr.json, locales/zh-CN.json, locales/zh-TW.json
Adds an "Export to PDF" option for Markdown notes. This feature behaves consistently with the other export options - however, due to its use of a hidden Electron window, it runs asynchronously. I've added support for output formatters to return Promises in `exportData.js` to support this feature.
Additionally, I have fixed `exportFolder.js` to actually wait for all notes to export. This wasn't a problem when note exporting was synchronous, but now it seems the extra wait time was causing tests to fail.
Fixes #2013.
- :radio_button: Feature …
=> Export a Markdown note as PDF

browser/main/NoteList/index.js
After following a link to an other note the folder /home (All Notes) will be selected. The expected behavior is that the storage folder of the requested note will be selected.
- …
=> Click a note link will now select the right folder note and not /home

readme.md
removed mobile app mention in the README
#2828
=> README: removed mobile app mention (#2828)

browser/lib/markdown.js
When calling into `markdown-it-plantuml` an additional parameter was being passed that results in custom PlantUML server configs not being picked up. A few lines lower is similar code for dittaa (via PlantUML server) that is missing this parameter and that works correctly
#2733 
- 🔘 Bug fix (Change that fixed an issue)
- :white_circle: I have written test for my code …
=> Removed erroneous parameter resulting in PlantUML server URL not being used

gruntfile.js
Fixed a grammatical error in gruntfile.js
Fixes a tiny grammatical error on the package description.
`The opensource note app for developer.` to `The opensource note app for developers.`
- …
=> Update productDescription in gruntfile.js to fix grammatical error

browser/components/CodeEditor.styl
Modification of the CodeEditor.styl to remove spellcheck squiggle from the dropdown menu itself.
Before there was a squiggle present under all options for selecting language of spell checker:
Before:
After:
- ✔️ Bug fix (Change that fixed an issue)
- ✔️ My code follows [the project code style](docs/code_style.md)
- ✔️ All existing tests have been passed
- ✔️ I have …
=> Spellcheck dropdown fix

browser/components/CodeEditor.js, browser/lib/markdown-toc-generator.js
After a line with a headline was changed
(the line should contains `# `) in a note with a toc, the toc generator will generate a new toc for this note.
Tested use cases:
- Edit a headline
- Remove multiple lines with a headline
- Paste lines with a headline
- Undo / Redo
#2782
- :large_blue_circle: Feature (Change that adds new functionality)
- :white_circle: I have …
=> Automatic update the table of content if available

browser/main/modals/NewNoteModal.js
add a lock sign to fix create new note twice when you click Button again before NewNoteModel was closed.
- :radio_button: I have attached a screenshot/video to visualize my change if …
=> fix newNoteModal create note twice after double click quickly

browser/components/CodeEditor.js, browser/lib/utils.js, tests/lib/utils.test.js
Now you can paste a valid markdown title with a link, eg: `# https://boostnote.io` and it gets the right page title.
#2907 
- :radio_button: I have attached a screenshot/video to visualize …
=> Fetch page title when paste valid markdown title with one valid URL

browser/main/store.js
I also can only reproduce the issue #2836 that on startup all tags are listed. I've changed the behavior that only tags from notes which are not trashed will be listed.
#2836 
- :large_blue_circle: All existing tests have been passed …
=> Initialize storage ignores now tags from skipped notes

browser/main/modals/PreferencesModal/ConfigTab.styl, browser/main/modals/PreferencesModal/Crowdfunding.js, browser/main/modals/PreferencesModal/Crowdfunding.styl, browser/main/modals/PreferencesModal/InfoTab.js, browser/main/modals/PreferencesModal/InfoTab.styl, browser/main/modals/PreferencesModal/SnippetTab.js, browser/main/modals/PreferencesModal/SnippetTab.styl, browser/main/modals/PreferencesModal/StoragesTab.styl
- This pull request will adjust all first headlines in all preferences tabs.
- At the Crowdfunding tab, the paragraph headlines are now real headlines (not only text with `###`)
- The snippet editor has now the right width of 100% (before 103%)
- :white_circle: I have written test for my code and it has …
=> Multiple minor changes at the preferences tabs

browser/components/MarkdownPreview.js
After change the current note to an other note, scrolling to the top of the new selected note. Now thats the same behavior as it implemented at the markdown split editor.
- …
=> After select an other note now scroll to top

browser/components/MarkdownPreview.js
https://github.com/BoostIO/Boostnote/issues/2875 Fixed zooming issue of galleries.
original:
After fixed:
Issue link: https://github.com/BoostIO/Boostnote/issues/2875
- 🔵 Bug fix (Change that fixed an issue)
- 🔵  My code follows [the project code style](docs/code_style.md)
- 🔵  All existing tests have been passed
- 🔵  I have attached a screenshot/video to visualize my …
=> Fixed bug-2875

browser/components/MarkdownPreview.js, browser/lib/consts.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js, extra_scripts/codemirror/theme/nord.css
This change adds the [Nord theme](https://github.com/arcticicestudio/nord) as an editor theme.
The following screen shot uses both Nord theme (UI and editor):
- #2722
- :radio_button: I have …
=> add Nord editor theme

browser/main/NoteList/index.js
Sorting titles with numbers tries to match float values of left and right titles at comparison. When both numbers are floats and not equal we can do a direct compare. In all other cases the full title will compare.
#2894
- …
=> Sorting notes alphabetically now sort starting numbers in titles right

docs/code_style.md
As mentioned in the issue I'd like to add a usage info for React Hooks.
I've copied the discussion part from the issue to the PR (see below)
#2999
- :white_circle: I have attached a …
=> Add React hooks section to code style guide

browser/components/MarkdownEditor.js, browser/components/MarkdownSplitEditor.js, browser/lib/getTodoStatus.js, tests/lib/get-todo-status-test.js
As described in issue, checkbox was unclickable in quotation.
Fixed regular expression on checkbox logic and added some test patterns.
This is my first contribution to OSS in my life. :smile: 
Please kindly point out if there is something wrong 🙏 
#2829
- :radio_button: I have written test for my code and it has …
=> Fix regular expression related checkbox logic

lib/main-menu.js
Fixes #3056. Add menu item "About" to "Help"
- ✅  Feature (Change that adds new functionality)
- ✅ My code follows [the project code style](docs/code_style.md)
- ✅  I have written test for my code and it has been tested
- ✅ All existing tests have been passed
- ✅ I have attached a screenshot/video to visualize my change if possible
=> Add menu item "About" to "Help"

browser/components/CodeEditor.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/HotkeyTab.js
Changes the mac hotkey to insert today's date & time from `Shift-Cmd-/` to `Alt-Cmd-/`
As described in #3074, `Shift-Cmd-/` opens the Help menu of the application.
#3074
- :radio_button: I …
=> Changed "insert date & time" hotkey on mac from Shift-Cmd-/ to Alt-Cmd-/

browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js
- Removed the default value of the customCSS on the ReactCodeMirror TAG in order to enable stored the CustomCSS value.
- Moved the default value to the ConfigManger.js.
#3041
- …
=> Fix Custom CSS Disappears After Saving

browser/components/MarkdownPreview.js
- Apply the method of fixLocalURLS before exporting to pdf.
#3033 
MacOS Mojave (10.14.5)
=> Fix export to PDF exporting corrupted images

browser/components/MarkdownPreview.js, browser/lib/consts.js, browser/main/DevTools/index.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js, browser/main/store.js, lib/main-window.js, tests/dataApi/copyFile-test.js
- Changed path usage with-out `../`
- Change development check on `process.env` - not perfect but that way we're getting production stuff if `NODE_ENV` is not defined. I think we can fix / improve that once we improved the build process.
Interface theming had a path issue as mentioned in the issue. 
Editor theming should be fixed as well.
#3018, #3042
-  :radio_button: My code follows [the …
=> Fix theme path issue

browser/lib/markdown.js, browser/main/lib/dataApi/attachmentManagement.js, tests/dataApi/attachmentManagement.test.js
This change fixes the gallery on windows.
- #2899
=> fix gallery on windows

browser/components/CodeEditor.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js, locales/da.json, locales/de.json, locales/en.json, locales/es-ES.json, locales/fa.json, locales/fr.json, locales/hu.json, locales/it.json, locales/ja.json, locales/ko.json, locales/no.json, locales/pl.json, locales/pt-BR.json, locales/pt-PT.json, locales/ru.json, locales/sq.json, locales/th.json, locales/tr.json, locales/zh-CN.json, locales/zh-TW.json
=> Fix 2892: Line wrapping

browser/main/TopBar/index.js
When I search for something and delete the search term from the search field, the search term doesn't stay highlighted in the editor panel.
[Deleted search term stays highlighted · Issue #3111 · BoostIO/Boostnote · GitHub](https://github.com/BoostIO/Boostnote/issues/3111)
- :white_circle: I have written test for …
=> Dont highlight search term if search field is emptied

browser/components/MarkdownEditor.js, browser/components/MarkdownSplitEditor.js
Before #3063 has merged, MarkdownEditor and MakrdownSplitEditor use CodeMirror always with 'lineWrapping' is on. #3063 has changed that behavior, so bring it back.
- #3145 
- :white_circle: …
=> MarkdownEditor and MarkdownSplitEditor always wrap lines

browser/components/NoteItem.js, browser/components/SideNavFilter.js, browser/components/TodoProcess.js, browser/main/Detail/ToggleModeButton.js, browser/main/SideNav/index.js
Some are caused by typo, some are caused by unused propType declarations
- :radio_button: Improvement (Change that improves the code. Maybe performance or development
=> Improvement: fix several propType errors raised by 'react.development.js'

browser/main/Main.js
The current Snippet Note Example's JavaScript file references a non-existent element with id `enjoy`. The HTML file has an element with id `hello`. I updated the JavaScript file to reference the same id (i.e., `hello`).
I know that the HTML file doesn't include the JavaScript file, so the two could be considered independent, but I think it's less confusing to keep IDs consistent.
- …
=> Fix JavaScript hello world example

browser/components/CodeEditor.js, browser/components/MarkdownEditor.js, browser/components/MarkdownSplitEditor.js
Avoid changing all CodeMirror instance's contents.
- partially fix #3163
=> Add `CodeEditor::setLineContent` method to manipulate line contents

browser/components/MarkdownPreview.js
The new Context Menu for markdown preview mode will only work if "switch preview" is not set to "on right click".
#3144
- :black_circle: Bug fix (Change that fixed an issue)
- :black_circle: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have attached a screenshot/video to visualize my …
=> Only show context menu if "switch preview" is not set to "on right click"

browser/components/CodeEditor.js
Digg a little into the situation that #3164 describes, turns out it has nothing to do with unicode characters.
The original `msg.length < 3` threshold may be out of performance concern, but since I don't have that much notes kept, it doesn't seem an issue to me.
=> optimize: should highlight any non-empty search query, fix #3164

browser/components/MarkdownPreview.js
This PR contains two commits modifying the MarkdownPreview component.
- 6438ff63 Mainly trying to fix #3023, but I guess there might be some more issues  related.
- 81e8f24d aims to improve performance by eliminating redundant calls.
I tried to write some tests for MarkdownPreview component with jest, but got error from `@rokt33r/js-sequence-diagrams` package.
```
FAIL  tests/components/MarkdownPreview.test.js
● Test suite failed to run
TypeError: _.isEmpty is not a function
at node_modules/@rokt33r/js-sequence-diagrams/dist/sequence-diagram-min.js:8:24486
at Object.<anonymous> (node_modules/@rokt33r/js-sequence-diagrams/dist/sequence-diagram-min.js:8:25685)
at Object.<anonymous> (browser/components/MarkdownPreview.js:47:27)
at Object.<anonymous> …
```
=> MarkdownPreview should scroll to top after selecting another note, also fix #3023

browser/main/Detail/MarkdownNoteDetail.js, browser/main/Detail/SnippetNoteDetail.js, browser/main/Detail/TagSelect.js
Changed routing to use `connected-react-router` by dispatching `push` to Redux store.
#3157
=> Fix routing for tag filtering (issue #3157)

browser/main/Detail/MarkdownNoteDetail.styl, browser/main/Detail/NoteDetailInfo.styl, browser/main/Detail/ToggleModeButton.styl
`user-drag: none` style from `MarkdownNoteDetail.styl` was applied to every `div` in the app and disabled dragging of notes.
Changed styling to address only the buttons/icons to disable the dragging of them.
One point where I'm not sure - was dragging of notes to trash icon supported by a previous app version because that's not working but I'm not sure if that was available before.
#3174
- …
=> Fix #3174: Enable dragging of notes

browser/components/MarkdownPreview.js
Disabled Javascript in the hidden printout electron window. We're currently not using Javascript in that Window, so it's OK to disable it.
If we would require JS later, we could also do sandboxing. But disabling is OK for now.
#3178
-  :radio_button: Bug fix (Change that fixed an issue)
-  :radio_button: My code follows [the project code style](docs/code_style.md)
- …
=> Fix XSS vulnerability after PDF export (issue #3178)

browser/main/Detail/MarkdownNoteDetail.js
Word count on Note Details was incorrect computed by counting words splitted by space. In the event of one word per line, the count was incorrect:
This was fixed by converting line breaks into spaces and then splitting them for count:
#888 
- :black_circle: Bug fix (Change that fixed an issue)
- :black_circle: My code follows [the project code style](docs/code_style.md)
- …
=> Fix #888 - Wrong word count due splitting

browser/main/modals/PreferencesModal/HotkeyTab.js
Error is thrown in [CodeEditor.js](https://github.com/BoostIO/Boostnote/blob/master/browser/components/CodeEditor.js#L39)  due to undefined `hotkey` input.
```js
function translateHotkey (hotkey) {
return hotkey.replace(/\s*\+\s*/g, '-').replace(/Command/g, 'Cmd').replace(/Control/g, 'Ctrl')
}
```
HotkeyTab should always emit complete hotkeymap.
- #3190 
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#3190: App blanks out after setting HotKey](https://issuehunt.io/repos/53266139/issues/3190)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>
=> fix: HotkeyTab accidentally set incomplete hotkey, related #3190

browser/main/SideNav/index.js
The sidebar contains a button to collapse the sidebar, but it is only visible when viewing the list of storages and notes. If the user is currently viewing the list of tags, the sidebar collapse button is not visible:
Notes view has always shown the sidebar collapse button:
The tags list now renders the sidebar collapse button as well:
Fixes #2097
-  :radio_button: Bug fix (Change that fixed an issue)
-  :radio_button: My code follows [the …
=> Add sidebar collapse button to sidebar while viewing the tags list

browser/main/modals/PreferencesModal/StorageItem.styl, browser/styles/index.styl
Fix for #3237 
Before:
After:
(fixed buttons to the right of My Storage Location for dracula theme)
- 🔘 Bug fix (Change that fixed an issue)
=> Dracula theme buttons in storage settings fix

.gitignore, browser/components/CodeEditor.js, browser/main/lib/ConfigManager.js
Just had a crack, not sure if this is production ready yet.
But, if anyone could take a look at it and let me know what do you think would be great.
#3160 
- :white_circle: I have attached a …
=> [Issue-3160] Add ability to sort lines with hotkey combination

browser/main/Detail/index.js
`location.pathname` regex match should be Stricter
- #3183
=> Stricter regex pattern in pathname matching, fix #3183

lib/main-app.js
Prevents throwing of exception when multiple instances of Boostnote are initiated.
Fixes #3241
=> Fix throwing of exception on multiple instances

browser/components/MarkdownPreview.js
Current implementation might mistake  external link with '#' for internal link. This PR fixes this.
Proper behavior should be:
```
- [Open in new browser](http://google.com/#viewport)
- [scrolls to internal heading](#Description)
```
- #3213 
=> fix: Can't open external browser in Markdown Preview with external link containing '#'

.travis.yml, package.json
So a reckless contributor will not forget to update jest snapshots 😅. (That's what happens when I try to fix tests' conflicts the first time in [3173](https://github.com/BoostIO/Boostnote/pull/3173))
=> npm 'test' script should contain jest tests

browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js
Fixed two issues.
1. Add a `MarkdownPreview::scrollTo` to call `body.scrollTo` instead of `window.scrollTo`, the implementation is similar to [PR 3293](https://github.com/BoostIO/Boostnote/pull/3293), but more thorough.
2. `scrollPastEnd` behavior is broken by addf9b92 , add some more style tweak to fix it.
- #3273 
- #3289 
=> Fix preview-window's scroll behavior, #3289

browser/main/lib/dataApi/createNoteFromUrl.js
Adds error handling for "New note from URL" dialog.
Fixes #3308
- Display error message on url not found
- Keep "New note" functional
- :radio_button: I have attached a screenshot/video to …
=> Add error handling to "New note from URL" dialog

browser/components/CodeEditor.js, lib/main.production.html
I defined some script tags and a stylesheet in `lib\main.development.html` but I didn't define them in `lib\main.production.html` then.
So I define them in `lib\main.production.html`.
And I removed a single quotation of the key names.
Because other key names in `browser\components\CodeEditor.js` were not enclosed in a single quotation.
#3147
- :radio_button: My code follows [the project …
=> Fix/fix to work markdownlint#3147

browser/lib/confirmDeleteNote.js, browser/main/SideNav/index.js
Fixes a typo, for OS confirmation dialogue types.
When permanently deleting a note, or when deleting a tag, a `warning` dialogue should be presented. But with the type of `ype` instead of `type`, a generic dialogue is presented.
Current behavior:
Expected Behavior:
No issues currently exist that identify the issue.
I could not replicate https://github.com/BoostIO/Boostnote/issues/2944, but the OS might be treating generic dialogues differently than warnings.
- :white_circle: …
=> Delete Dialog: typo for the "type" property

package.json, yarn.lock
Bumped Mermaid version to support state diagrams.
Did sanity check whether mermaid is still working.
sequence diagram like before:
new added state diagram:
------ 
<details>
<summary>
<b>old description</b>
</summary>
This PR  uses the library: https://www.npmjs.com/package/state-machine-cat version 5.3.6
Do we want to add this dependency? 
By adding this dependency we gain the ability to create state graphs by adding it as a `state` block in the markdown editor.
\`\`\`state
initial => todo;
todo    => doing;
doing   => done;
done    => final;
\`\`\`
leads to this:
Without this we have the rely on the dependencies we are using right now, Mermaid and Plantuml.
Why they are not sufficient for this use-case can be found here further: #2933 
https://gfycat.com/marvelousexcitablekoala
speed up …
=> feature state diagram: add state diagram to markdown preview

browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/InfoTab.js, lib/main-app.js, locales/en.json, tests/helpers/setup-electron-mock.js
=> Ability to stop auto update

browser/components/MarkdownPreview.js
Changed from re-rendering the Markdown (which doesn't render the SVGs from Mermaid), to referencing the Preview DOM that's already rendered, thereby incorporating the already produced SVGs.
- https://github.com/BoostIO/Boostnote/issues/2648
- https://github.com/BoostIO/Boostnote/issues/3229
- https://github.com/BoostIO/Boostnote/issues/3202
- https://github.com/BoostIO/Boostnote/issues/3349
[TestText.txt](https://github.com/BoostIO/Boostnote/files/3775205/TestText.txt)
[TestPDF.pdf](https://github.com/BoostIO/Boostnote/files/3775206/TestPDF.pdf)
HTML and MD files are not supported by Github, so am not able to attach.
- :radio_button: Improvement …
=> Export: uses markdown preview dom. Supports diagrams

lib/main-menu.js
I think `macOS ? 'Command+E' : 'Control+E'` is redundant condition, and we should use `CommandOrControl+E`.
- 🔘  Improvement (Change that improves the code. Maybe performance or development improvement)
- 🔘 My code follows [the project code style](docs/code_style.md)
=> remove redundant conditions of macOS in main-menu

browser/components/MarkdownPreview.js, locales/cs.json, locales/da.json, locales/de.json, locales/en.json, locales/es-ES.json, locales/fr.json, locales/it.json, locales/pt-BR.json, locales/pt-PT.json, locales/sq.json
Add the `Ok` button to confirm and close the export message box.
#3344 
- :radio_button:My code follows [the project code style](docs/code_style.md)
=> Add Ok button to export confirmation box

browser/components/NoteItem.js, package.json, yarn.lock
This PR adds a package to render emojis in the notes list.
It fixes the issue #3338 
=> Fix emoji render on notes list

readme.md
This PR is a small update to the readme. For user who land on [this page](https://github.com/BoostIO/Boostnote) it is not clear where to download the files to install Boostnote.
=> Added link to downloads

lib/main-menu.js
Simple PR to add a link to the Boostnote wiki page under the help menu as requested in #3435
=> Added Wiki Link to Help Menu

docs/build.md
Add Traditional Chinese option to build.md
=> Add Traditional Chinese option to build.md

browser/main/lib/ConfigManager.js, prettier.config
Bug fix (sets tabWidth to 2 on prettier configuration and ConfigManager so checkboxes can be clikable).
#3361 
- :white_circle: I have attached a screenshot/video to visualize my change if …
=> Fix prettier configuration

docs/zh_TW/build.md
Complete translation.
Sync with English version.
[1] https://github.com/BoostIO/Boostnote/blob/master/docs/build.md.
Update zh_TW translation of build.md.
- :black_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)
- :white_circle: I have attached a …
=> Update zh_TW translation of build.md

docs/build.md
Includes the required build dependency packages to build the app
Most people tend to overlook:
> After installing the supported version of `node` and `npm`, **install build dependency** packages.
Including it gives them a heads up.
#3278 
https://github.com/BoostIO/Boostnote/issues/3278#issuecomment-545151294
- 🔘 Documentation change (Change that modifies documentation. Maybe typo fixes)
=> Include build dependency packages cmds on build docs

browser/main/NoteList/index.js, browser/main/lib/ConfigManager.js, resources/icon/icon-up.svg
This PR adds two buttons next to the existing "list style" buttons which allow the user to specify whether the note list should be sorted in ascending or descending order.
- :radio_button: I …
=> Added sorting direction buttons

browser/components/MarkdownPreview.js, browser/components/markdown.styl
**Update:**
I made changes to all headings. Now, if you keep typing lines, some horizontal lines disappear randomly on 80% and 90% views. I am looking into other markdown css at the moment
https://github.com/BoostIO/Boostnote/issues/3211
- …
=> [WIP]h1 padding bottom value changed

browser/components/StorageList.styl
Scroll bar and search bar cannot be displayed when there are many folders.
#3486 Can't scroll in sidebar 
before
after
When the scroll bar is hidden  
- :radio_button: I have attached a …
=> Unable to scroll when there are many folders  

PULL_REQUEST_TEMPLATE.md
This PR update the pull request template to include necessary question about UI or keybinding
=> updated PR template

browser/components/StorageItem.js, browser/components/StorageItem.styl, browser/main/SideNav/StorageItem.js
Tooltip misplaced when scrolling down.
https://github.com/BoostIO/Boostnote/pull/3490#pullrequestreview-364499729  
- :radio_button: I have attached a screenshot/video to visualize my change …
=> Tooltip misplaced

browser/components/MarkdownEditor.js, browser/components/MarkdownPreview.js, browser/main/Detail/MarkdownNoteDetail.js, browser/main/lib/ConfigManager.js, browser/main/modals/PreferencesModal/UiTab.js
This pr makes rtl completely optional and changes RTL hotkey for Windows and Linux app. 
Fixes #3493, #3485
- :white_circle: This PR will modify the UI or affects the UX
- :white_circle: This PR will add/update/delete a keybinding
=> Make RTL optional

browser/components/MarkdownPreview.js, browser/main/Main.js, extra_scripts/codemirror/addon/hyperlink/hyperlink.js, extra_scripts/codemirror/mode/bfm/bfm.js, extra_scripts/codemirror/mode/gfm/gfm.js, lib/main.development.html, lib/main.production.html
I've added the missing link handling for `:tag`, `:line` & `:note` links in editor (ctrl+click handling). This branch is based on branch `feature-tag-links` so this PR is waiting for PR #3002 to be approved/merged.
I first wanted to move the script from MarkdownPreview link handling to a file that we can use at both location but I think it's OK to have some code duplication at two locations.
It's also not identical code but pretty similar. If there is a location where I can put the `specialLinkHandler` method, I can add it but I think it's also OK like I have added it.
You can test the link handling with the following Markdown (requires some updates so tags & notes are available):
```md
- Item 1 [#Typescript](:tag:#Typescript)
- Item 2 [#1st tag](:tag:#1st)
[XSS …
```
=> Fix 3364 editor ctrl click

browser/main/lib/ThemeManager.js
This change fixes the broken ui themes.
- #3554
- :white_circle: This PR will modify the UI or affects …
=> fix broken ui themes

browser/components/CodeEditor.js
This change fixes the unwanted deletions of attachments.
The issue is due to that a note can be changed between the editor has lost its focus and when the function removing unused attachments is run. The delay of 30s between the focus lost and cleanup was introduced for #3103.
How to reproduce the issue:
- click on the editor
- click on image you want to add to the note (the editor has lost its focus, the cleanup function will run in 30s)
- drag the image into the note but do not click in the editor
- wait 30s
- the image will have been deleted. (the image is still shown due to cache)
The fix:
Every time that the note is changed, the call to the cleanup function is cancelled.
- #3203
- #3424
- :white_circle: Breaking change (Change …
=> fix unwanted deletion of attachments
