BoostIO/Boostnote

- browser/main/NoteList/index.js
I was fixed "Can't delete last note in NoteList".
> Fix delete last note

- docs/build.md
Hi,
I tried to build and found following points to improve the build instruction document.
Could you check it?
- Added an instruction `npm install` which is required to build.
- Added `$` at the heading of each command in order to distinguish between commands and others.
- Fixed typo. "@" to "`"
> Fix and improve docs

- browser/main/TopBar/index.js
- docs/build.md
- lib/main-menu.js
- lib/main-window.js
> Various updates

- lib/main-window.js
Got this syntax error the first time compiling/running Boostnote.
> Fix syntax error (unexpected token)

- readme.md
Updated the look of the readme and fixed some english errors.  Ran into a slight issue w/ how markdown renders html so I had to push a few more changes than expected.
> Updated readme english & reformatting

- lib/main-menu.js
Without the menu some people are unable to access certain functionality.  Until we are able to provide that functionality another way, this should fix the problem.
> Adding menu back in temporarily to fix shortcuts.

- docs/build.md
Just fixed a trivial typo.
어쩌다 발견하게 됐네요. :)
> Just fix a trivial typo.

- readme-ja.md
Link, typo and list of Author & Maintainer
> Updated of Japanese readme.

- readme.md
add sota1235, Kohei TAKATA and Kazu Yokomizo.
> Update Author & Maintainer

- lib/main-window.js
- package.json
Hello, I dealt with https://github.com/BoostIO/Boostnote/issues/207
> refs #207 Keeps window size

- browser/main/Detail/FolderSelect.js
- browser/main/Detail/FolderSelect.styl
- browser/main/Detail/LastUpdatedString.styl
- browser/main/Detail/MarkdownNoteDetail.js
- browser/main/Detail/NoteDetailInfo.styl
- browser/main/Detail/SnippetNoteDetail.js
- browser/main/Detail/SnippetNoteDetail.styl
- browser/main/Detail/StarButton.styl
- browser/main/Detail/TagSelect.styl
- browser/main/StatusBar/index.js
- docs/build.md
- gruntfile.js
- package.json
- Update document.
- Remove unneeded parameter on `package.json`
> Add folder selector on note detail.

- browser/components/CodeEditor.js
- browser/components/MarkdownEditor.js
- browser/finder/NoteDetail.js
- browser/main/Detail/SnippetNoteDetail.js
- browser/main/lib/ConfigManager.js
- browser/main/modals/PreferencesModal/ConfigTab.styl
- browser/main/modals/PreferencesModal/UiTab.js
- lib/finder.html
- lib/main.html
Hello, finally I add vim-keymap to boostnote.
reference: https://codemirror.net/2/demo/vim.html
> Adds vim keymap setting

- readme-ja.md
- readme.md
en: update to todolist link
ja: edit all
> Update to readme

- browser/main/modals/InitModal.styl
- browser/main/modals/NewNoteModal.js
- browser/main/modals/NewNoteModal.styl
Updated MakeNoteModalEscButton design.
> changeEscButton

- browser/finder/index.js
Hi, this PR is for handling https://github.com/BoostIO/Boostnote/issues/246. It occurs on blur. Thus I removed blur handler.
> Fix a Bug when using the Finder Window with markdown Notes

- browser/finder/FinderMain.styl
- browser/main/modals/NewNoteModal.styl
correction MakeNote EscButton in darkmode
> Feature esc button

- browser/main/SideNav/SideNav.styl
> Fix style for side nav

- lib/main-app.js
> refs #239 [Fix] cannot open finder with using hotkey on windows

- lib/finder-window.js
> Fix windows taskbar icon

- browser/main/modals/RenameFolderModal.styl
> Fix font color for dark theme rename folder modal

- browser/main/NoteList/index.js
- lib/main-menu.js
This PR adds a shortcut which jumps to a top of notes by Ctrl+G. Any ideas for the shortcut?
> Add a shortcut which jumps to top by Ctrl-G

- browser/components/markdown.styl
- browser/lib/markdown.js
- package.json
> Remove markdown-it-toc because an errors are happening

- browser/components/CodeEditor.js
When you hit enter on a line with a bullet, you get a new one on the new line.
Also when you hit tab after a bullet, it automatically indents.
It makes typing with bullets much more pleasant.
> Smart bullets

- docs/build.md
- docs/debug.md
- docs/jp/build.md
- docs/jp/debug.md
Hi. I added documents. Please point out wrong points.
> Modify and add documents

- lib/finder-menu.js
- lib/main-menu.js
I think it is more consistent to have the same notation everywhere.
> Uniform the accelerator notation

- contributing.md
I edited contributing.md. The reason why I didn't add `issue template` is because I want to manage to keep the style of issue freely.
> Edit contributing.md

- readme.md
Made some small styling tweaks for greater uniformity within the readme document.
Also reworded a few sections to read more clearly.
> Updated readme file to read more cleanly in English

- browser/main/modals/PreferencesModal/InfoTab.js
> Fix typo in Infotab

- docs/build.md
- docs/debug.md
I've adjusted the wording in the build and debug files to flow better and make more sense in English.
> Changed wording in build.md and debug.md

- browser/main/modals/InitModal.js
Made a few small tweaks so the wording makes more sense to English speakers.
> Updated initial pieces of text to read more clearly in English

- browser/main/Detail/SnippetNoteDetail.styl
- lib/main.html
> Fix the loading layout

- browser/main/modals/InitModal.js
InitModal has a close button. However if you use it, you cannot make a storage.  So, I think that close button in InitModal is Unnecessary. I delete it.
> delete the escButton in the InitModal

- browser/main/modals/PreferencesModal/HotkeyTab.js
Added `Shift` to Hints in `HotkeyTab.js`.
> Added `Shift` to HotkeyTab.js

- browser/main/modals/PreferencesModal/InfoTab.js
- readme-ja.md
- readme.md
Change the donation link patreon to Bountysource.
> Change donate link

- browser/components/NoteItem.styl
- browser/components/NoteItemSimple.styl
modify dark theme only
<-old --- new ->
> Change noteitem border color

- browser/components/ModalEscButton.js
- browser/components/ModalEscButton.styl
- browser/main/modals/CreateFolderModal.js
- browser/main/modals/CreateFolderModal.styl
- browser/main/modals/InitModal.js
- browser/main/modals/InitModal.styl
- browser/main/modals/NewNoteModal.js
- browser/main/modals/NewNoteModal.styl
- browser/main/modals/PreferencesModal/PreferencesModal.styl
- browser/main/modals/PreferencesModal/index.js
- browser/main/modals/RenameFolderModal.js
- browser/main/modals/RenameFolderModal.styl
Boostnote has many modals and it have esc button.
before, We made esc button in all modals. So I made react component of esc Button. This can be reused.
> made escButton ReactComponent

- tests/fixtures/TestDummy.js
- tests/lib/search-test.js
Add tests
Refs: https://github.com/BoostIO/Boostnote/pull/600
> Add tests for searchFromeNotes()

- tests/e2e/spectron.js
> Revert "Add e2e tests"

- contributing.md
I translate contributing.md content to korean.
> Translate contributing.md to korean

- browser/main/modals/PreferencesModal/UiTab.js
- lib/finder.html
- lib/main.html
> Add emacs keymap

- browser/finder/index.js
- browser/main/Detail/MarkdownNoteDetail.js
- browser/main/Detail/SnippetNoteDetail.js
- browser/main/Detail/TagSelect.js
- browser/main/Main.js
- browser/main/lib/AwsMobileAnalyticsConfig.js
- browser/main/modals/CreateFolderModal.js
- browser/main/modals/NewNoteModal.js
- package.json
- webpack-production.config.js
- webpack.config.js
- yarn.lock
Boostnote collect data by mixpanel, now. But, We want to use amazon mobile analytics for collecting data.
> Feature amazon mobile analytics

- browser/lib/htmlTextHelper.js
- tests/lib/html-text-helper-test.js
As you see, I added an entity (`$`) to the methods to handle the issue below.
refs: https://github.com/BoostIO/Boostnote/issues/619
> Fix a rendering bug

- browser/main/Main.js
- browser/main/lib/AwsMobileAnalyticsConfig.js
> Disable awsAnalytics on develop

- browser/main/Main.js
I know this is the tiniest possible contribution but I needed this to be able to build the dev stack so I figured might as well push it.
You can see the error actually show up in the [travis build](https://travis-ci.org/BoostIO/Boostnote/jobs/242118774#L985)
> Fix typo in includes

- browser/main/lib/AwsMobileAnalyticsConfig.js
I fix initialize logic of analytics.
See also: #634
> Fix initialize logic of analytics

- browser/main/lib/AwsMobileAnalyticsConfig.js
> Exclude auth of aws only production

- browser/components/CodeEditor.js
- lib/main.html
- package.json
- yarn.lock
Because of its high demand, I finally implemented it.
> Add search-box

- browser/main/index.js
> Fix an error on click event

- browser/components/MarkdownEditor.js
- browser/finder/NoteDetail.js
- browser/lib/findStorage.js
- browser/main/lib/dataApi/copyImage.js
- browser/main/lib/dataApi/createFolder.js
- browser/main/lib/dataApi/createNote.js
- browser/main/lib/dataApi/deleteFolder.js
- browser/main/lib/dataApi/deleteNote.js
- browser/main/lib/dataApi/moveNote.js
- browser/main/lib/dataApi/renameStorage.js
- browser/main/lib/dataApi/updateNote.js
- tests/lib/find-storage-test.js
It's refactoring :recycle:.
There were many similar lines.
There are less similar lines.
> Add find storage path module

- ISSUE_TEMPLATE.md
I wanted to stress `the developer tool open` in ISSUE_TEMPLATE.
Not everybody did.
I wish everybody will do.
> Stress words in ISSUE_TEMPLATE

- .eslintrc
- browser/main/Detail/SnippetNoteDetail.js
- browser/main/Main.js
- browser/main/modals/PreferencesModal/InfoTab.js
This PR is for refactoring pointed by eslint-plugin-react :recycle:
* Rename snippet
* Change mode of a snippet
* Change code of a snippet
* Work fullscreen
> Fix by eslint react

- browser/components/MarkdownPreview.js
> Fix layout

- browser/main/modals/PreferencesModal/StoragesTab.js
Put a link for cloud integration: https://github.com/BoostIO/Boostnote/wiki/Cloud-Syncing
> Add link for cloud integration

- browser/main/NoteList/index.js
> Fix typo addNotes to addNotesFromFiles

- browser/main/modals/PreferencesModal/InfoTab.js
My first pull request; just to fix this grammar in English. Mostly setting this up to get the flow of open source and start a conversation. Hope to send another one soon :)
> Fix grammer in InfoTab

- browser/components/MarkdownPreview.js
- browser/components/markdown.styl
> Change font color in code at default theme

- browser/components/markdown.styl
> Fix font color in code block

- docs/debug.md
- docs/ko/build.md
- docs/ko/debug.md
Add recent translation for korean developer
> Add recent translated korean developement & debug docs

- browser/main/NewNoteButton/NewNoteButton.styl
> Fixed button protrustion when creating a new folder.

- browser/main/modals/InitModal.js
Fixes #967
Used the correct handler for closing the modal. I don't think I'l be able to demonstrate this using pictures so maybe try running it locally, sorry.
> Use the correct handler for closing the modal.

- browser/main/NoteList/index.js
Add `getTargetIndex()` to reduce code.
> Add getTargetIndex() and replece them

- browser/main/modals/PreferencesModal/Crowdfunding.js
- browser/main/modals/PreferencesModal/index.js
> Remove unused vars

- ISSUE_TEMPLATE.md
I changed the sentence in order to fix its unfriendliness.
> Change ISSUE_TEMPLATE because it seems unfriendly

- Backers.md
- browser/main/modals/PreferencesModal/Crowdfunding.js
- browser/main/modals/PreferencesModal/InfoTab.js
- readme.md
https://opencollective.com/boostnoteio
> Change crowdfunding Bountysource to OpenCollective.

- browser/main/modals/PreferencesModal/ConfigTab.styl
- browser/main/modals/PreferencesModal/UiTab.js
> Add notification at UI tab

- lib/main-window.js
> Not quit app using close button on Mac

- browser/components/CodeEditor.js
> Fix CI error

- docs/build.md
- docs/jp/build.md
This docs update explains the function added in #266.
It is available in English and Japanese. (I can not use other languages ... sorry)
Could you check/review this PR? Thanks!
> [doc] Add how to creating distribution packages(deb, rpm)

- browser/main/Detail/PermanentDeleteButton.js
- browser/main/Detail/SnippetNoteDetail.js
> Fix button layout in Trash

- lib/main.html
> Fix windows scrolling bug

- browser/main/Detail/SnippetNoteDetail.styl
- browser/main/StatusBar/StatusBar.styl
> Fix status bar layout

- package.json
Fixed issues #1029 
**Refer**
jGleitz/markdown-it-kbd#3
> Updated markdown-it-kbd to 1.1.1 from 1.1.0

- browser/main/modals/InitModal.js
fixed #1171 
this change makes only ESC key can close the initmodal window.
> fix anykey can close the initmodal window issue

- browser/components/NoteItem.styl
> Fix note list layout

- browser/components/StorageItem.js
- browser/main/SideNav/StorageItem.js
I fixed emoji garbling on folded sidebar.
Before:
After:
> Fix surrogate pairs garbling on folded SideNav

- browser/main/modals/InitModal.js
- browser/main/modals/InitModal.styl
- browser/styles/index.styl
> Fix layout at initial modal

- browser/finder/index.js
The latest version(v.0.8.18) cannot open finder.
I fixed the bug.
> fix bug cannot open finder.

- browser/components/MarkdownPreview.js
> fixed incorrect fontFamily for multiple fonts

- browser/components/SideNavFilter.styl
Fix https://github.com/BoostIO/Boostnote/issues/1191#issuecomment-349934313
> Fix the folded side bar layout

- browser/components/SnippetTab.js
- browser/main/Detail/SnippetNoteDetail.js
implements Feature Request #842 - drag + drop of snippet tabs
> implemented drag/drop for tabs

- browser/components/NoteItem.styl
- browser/components/NoteItemSimple.styl
- browser/components/SideNavFilter.styl
- browser/components/markdown.styl
- browser/finder/ipcClient.js
- browser/main/Detail/MarkdownNoteDetail.styl
- browser/main/Detail/NoteDetailInfo.styl
- browser/main/Detail/SnippetNoteDetail.styl
- browser/main/Main.js
- browser/main/NewNoteButton/NewNoteButton.styl
- browser/main/NoteList/NoteList.styl
- browser/main/SideNav/SideNav.styl
- browser/main/TopBar/TopBar.styl
- browser/main/lib/ConfigManager.js
- browser/main/modals/PreferencesModal/UiTab.js
- browser/styles/index.styl
> Add the Solarized Dark Theme

- browser/main/Main.js
- browser/main/lib/AwsMobileAnalyticsConfig.js
we open Boostnote, when disconnection Internet. Then, console shows many error message(like below the image).
So, I detect internet disconnection, and stop sending event.
> Detect ama errors

- browser/main/Detail/MarkdownNoteDetail.js
- browser/main/Detail/MarkdownNoteDetail.styl
- resources/icon/icon-mode-markdown-off-active.svg
- resources/icon/icon-mode-split-on-active.svg
> Fix switch button layout

- browser/main/store.js
* Deleting a starred item will now update the starred count in the side nav. (delete from starred set)
* Restoring a starred item will add it the the starred set again.
Fix: #1326
> Fix starred item count

- browser/components/MarkdownSplitEditor.js
> fix bug that config of editorIndentSize is not working.

- browser/main/Detail/MarkdownNoteDetail.js
> fix bug when add tag, disappear note.

- browser/main/modals/PreferencesModal/StorageItem.styl
> Fix the Solarized Dark Styling

- browser/components/SideNavFilter.styl
> Fix the folded layout on side bar

- browser/main/Detail/InfoPanel.js
- browser/main/Detail/InfoPanel.styl
implements #1405 - question: do we want to show the copy notification, like in the markdown preview once the button has been clicked and the link has been copied to the clipboard?
> added button for copy note link

- browser/main/NoteList/index.js
implements #1398 - use filename as note title (without extension)
> name note to imported file

- browser/main/modals/PreferencesModal/ConfigTab.styl
> make save button position:fixed

- browser/components/MarkdownPreview.js
> added encoding meta tag

- browser/main/Detail/MarkdownNoteDetail.js
- browser/main/Detail/MarkdownNoteDetail.styl
- resources/icon/icon-previewoff-off.svg
- resources/icon/icon-previewoff-on.svg
> Fix the editor lock button layout

- package.json
- yarn.lock
> Update KaTeX library from 0.7.1 to 0.8.3

- browser/lib/context.js
- browser/main/NoteList/index.js
- browser/main/SideNav/StorageItem.js
- browser/main/modals/PreferencesModal/Crowdfunding.js
- browser/main/modals/PreferencesModal/HotkeyTab.js
- browser/main/modals/PreferencesModal/InfoTab.js
- browser/main/modals/PreferencesModal/StoragesTab.js
- browser/main/modals/PreferencesModal/UiTab.js
- browser/main/modals/PreferencesModal/index.js
- browser/main/store.js
Just a few minor changes in wording and grammar, to improve clarity and professionalism overall
> Improved overall wording and grammar of preferences

- LICENSE
- browser/main/modals/PreferencesModal/InfoTab.js
- contributing.md
We changed the company name "Maisin&Co" to "BoostIO".
> Change the company name

- browser/components/NoteItem.js
- browser/components/NoteItemSimple.js
- browser/main/NoteList/index.js
All restrictions of pin functionality were removed. Now user can see pinned notes and also pin notes right from 'home'. Technically, a note still pins to the storage it belong.
#1506
> Show pinned notes in All notes view and allow to pin them there

- docs/de/build.md
- docs/de/debug.md
- docs/debug.md
- docs/fr/build.md
- docs/fr/debug.md
some german improvements and corrections of the translation
> German translation: minor corrections

- browser/components/CodeEditor.js
This fixes the PR that was broken in 808d193
> Fixed bad merge; closes #1586; related to #1521

- lib/main-menu.js
> add Toggle FullScreen feat + shortcut

- browser/lib/markdown.js
> Add table and details stuff to whitelist

- browser/lib/markdown.js
FYI : https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb
> Use same settings of github

- browser/components/markdown.styl
Fix #1705 
**Before:**
**After:**
> Wrap long LaTeX formula in Preview

- lib/main.html
This is to fix first point of [issue#1003](https://github.com/BoostIO/Boostnote/issues/1003)
> Fix #1003 Add CodeMirror addon

- browser/main/NoteList/index.js
Fixes #1739 
Sorry for re-opening this pull request. I wanted to use feature-branches in my repo and accidentally reset the master branch so the original pull request was deleted.
> Clean up trash context menu

- browser/components/StorageList.js
- browser/components/StorageList.styl
- browser/main/SideNav/index.js
> fix folded storagelist width

- browser/main/Main.js
Hi Boostnote team,
Thanks for this amazing app. I noticed some code repetitions that can be avoided, I don't know if they was there on purpose or by accident. If there is a reason for them to stay there then please tell me why, maybe I can learn something from this :smile:
> Edited theme and language init code to avoid code repetition

- browser/lib/i18n.js
- browser/main/modals/PreferencesModal/UiTab.js
> Fixed change some languages

- browser/main/NoteList/index.js
> fix deprecation warning

- browser/components/CodeEditor.js
- browser/main/lib/dataApi/copyImage.js
This PR is a fix for this issue: https://github.com/BoostIO/Boostnote/issues/1822
> Fixed image not displaying after paste

- browser/components/SideNavFilter.js
> Empty trash menu working in sidebar folded

- browser/components/MarkdownPreview.js
Scrolling to the target in case the link points in the same note.
> fix internal note link bug #1820

- browser/main/SideNav/index.js
- browser/main/store.js
> Not showing unassigned tag in taglist 

- browser/main/store.js
> fix moving note across different storage bug

- locales/ja.json
> fix 'About' translation in ja.json

- browser/lib/markdown.js
- browser/main/lib/ConfigManager.js
- browser/main/modals/PreferencesModal/UiTab.js
- locales/da.json
- locales/de.json
- locales/en.json
- locales/es-ES.json
- locales/fa.json
- locales/fr.json
- locales/hu.json
- locales/it.json
- locales/ja.json
- locales/ko.json
- locales/no.json
- locales/pl.json
- locales/pt-BR.json
- locales/pt-PT.json
Implement #1592
I have put the custom plantuml setting in preview config. I'm not sure it is the right place or not. 
If you don't like this, please let me know. I will fix it.
> Configurable plantuml server

- browser/components/SideNavFilter.styl
- browser/components/StorageItem.styl
- browser/main/SideNav/StorageItem.styl
> standardrize sidebar tooltips

- browser/components/MarkdownPreview.js
> open external browser once in clicking the link

- browser/components/MarkdownEditor.js
> Fix typo of MarkdownEditor.js

- package.json
- yarn.lock
**Motivation for PR**
When I submitted my previous PR updating the project from Electron 1.8.x to 2.0.x I forgot to actually update the packaging Electron version. This PR fixes that and also updates to the latest version.
> Update Electron to v2.0.3

- package.json
- yarn.lock
Fixed #2081 and part of #1864(timing diagram)
> plantuml non-english character support and timing diagram support

- browser/main/modals/PreferencesModal/SnippetList.js
- browser/main/modals/PreferencesModal/SnippetTab.js
- browser/main/modals/PreferencesModal/SnippetTab.styl
> Improve snippets ui

- browser/components/MarkdownPreview.js
- browser/lib/markdown-it-sanitize-html.js
> Add sanitization for code fence

- browser/components/MarkdownPreview.js
- browser/components/markdown.styl
- browser/lib/markdown.js
- package.json
- yarn.lock
Support all [chartjs](https://www.chartjs.org) charts #862
See for [Chart types](http://www.chartjs.org/docs/latest/charts/) 
```
```chart
{
"type": "line",
"data": {
"labels": [
"January",
"February",
"March",
"April",
"May",
"June",
"July"
],
"datasets": [
{
"label": "# of bugs",
"fill": false,
"lineTension": 0.1,
"backgroundColor": "rgba(75,192,192,0.4)",
"borderColor": "rgba(75,192,192,1)",
"borderCapStyle": "butt",
"borderDash": [],
"borderDashOffset": 0,
"borderJoinStyle": "miter",
"pointBorderColor": "rgba(75,192,192,1)",
"pointBackgroundColor": "#fff",
"pointBorderWidth": 1,
"pointHoverRadius": 5,
"pointHoverBackgroundColor": "rgba(75,192,192,1)",
"pointHoverBorderColor": "rgba(220,220,220,1)",
"pointHoverBorderWidth": 2,
"pointRadius": 1,
"pointHitRadius": 10,
"data": [
65,
59, …
> Add chartjs support

- browser/lib/markdown.js
> add Ditaa support

- browser/main/modals/PreferencesModal/SnippetList.js
Fixed https://github.com/BoostIO/Boostnote/issues/2280
> Fixed snippet list bug

- browser/components/SnippetTab.styl
> add Monokai style for SnippetTab

- browser/styles/index.styl
> Fix text not readable for Monokai theme while creating new folder

- browser/components/markdown.styl
> Fix scroll for long table

- browser/main/modals/PreferencesModal/ConfigTab.styl
> Make notification sticky to the Save button

- browser/main/Detail/SnippetNoteDetail.js
- yarn.lock
This change fixes the tag autocompletion in a snippet note.
> fix tag autocomplete in snippet note

- browser/main/NoteList/index.js
Refs #1833 
This is my first PR to Boostnote, I am happy to hear feedback!
> fix a bug causing right click to copy a note -- fixes #1833

- browser/main/modals/PreferencesModal/Blog.js
- browser/main/modals/PreferencesModal/HotkeyTab.js
- browser/main/modals/PreferencesModal/UiTab.js
I noticed that a past tense error message would fit better in most cases.
> improve error message grammar

- browser/main/modals/PreferencesModal/SnippetTab.js
This adds a button to copy snippets.
Solves #2108
> Add a Copy button the Snippets tab

- browser/components/MarkdownPreview.js
> Moved custom CSS to bottom of style definitions so that it has higher precedence.

- browser/components/MarkdownPreview.js
> Prevent empty printed page with scroll-past-end

- lib/main.html
This change enables folding on headings.
- #2295
> fold headings

- readme.md
Related to PR #2584 
Centered build badge w/ fixed link.
> Fixed Build Badge Alignment w/ Fixed link

- .editorconfig
> Https link to EditorConfig.org

- browser/components/SnippetTab.styl
- browser/main/Detail/SnippetNoteDetail.styl
- browser/styles/index.styl
This PR implements feature request [#2095](
https://github.com/BoostIO/Boostnote/issues/2095). It makes the code snippet tabs more pronounced and easier to identify which tab is active. 
Cleaner more distinctive tabs in snippets. [#2095](
https://github.com/BoostIO/Boostnote/issues/2095)
- :white_circle: I have …
> Update tabs ui

- browser/main/Main.js
This change updates the min width of the note list.
- #2715
> fix min width of note list

- LICENSE
- browser/main/modals/PreferencesModal/InfoTab.js
- readme.md
> Update copywrite year

- browser/lib/SnippetManager.js
Fix bug from https://github.com/BoostIO/Boostnote/pull/2864#issuecomment-475238509
> Fix wrong binding

- .travis.yml
Make the build environment version (node and npm) on TravisCI the same as the version described in the latest document.
https://github.com/BoostIO/Boostnote/blob/master/docs/build.md#environments
#1602 
- :red_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :red_circle: My code follows [the project code style](docs/code_style.md)
- :red_circle: I have written test for my code and it has been tested
- :red_circle: All existing tests have been …
> Upgrade Travis CI node and npm versions

- browser/main/NoteList/index.js
- browser/main/lib/dataApi/attachmentManagement.js
- package.json
Imports the markdown's images when a new markdown file is imported
#2385 
> importAttachments

- browser/components/CodeEditor.js
Added new shortcuts:
- Ctrl+/ to inserts today's date
- Shift+Ctrl+/ to inserts today's date & time
- #1765 
- got error when "npm run test" on Windows environment.
- :radio_button: I have …
> Add "Ctrl + /" and "Shift + Ctrl + /" to insert today's date and time

- browser/components/NavToggleButton.js
- browser/components/NavToggleButton.styl
This PR is a continuation work to #2450 and will close it.
- PR #2450
> Increase arrow size on sidebar

- browser/main/modals/PreferencesModal/UiTab.js
Add a default value for Custom CSS editor
#2789 
- ⚪️Bug fix (Change that fixed an issue)
- ⚫️Improvement (Change that improves the code. Maybe performance or development improvement)
- ⚫️My code follows [the project code style](docs/code_style.md)
> add default value to custom CSS editor

- locales/es-ES.json
Fixed typo on string 137, plus some translation done
There is no previous issue fixed. There is no break on code.
- :white_circle: I have attached a screenshot/video to visualize my change …
> Fixed typo on string 137

- browser/lib/Languages.js
Fixed code formatting
There is no issue fixed. There is no break on code.
- :large_blue_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)
> Fixed formatting

- browser/main/Detail/MarkdownNoteDetail.styl
Changed some styles to prevent button icons from being dragged or selected.
- 🔘 Bug fix (Change that fixed an issue)
- 🔘 My code follows [the project code style](docs/code_style.md)
- 🔘 I have attached a screenshot/video to visualize my change if possible
> Make buttons undraggable

- browser/main/Detail/MarkdownNoteDetail.js
Use the right unlock/lock icon in markdown editor split view
#1760
> Update lock/unlock icons in editor #1760

- browser/components/MarkdownSplitEditor.styl
Define "border-left" and apply theme color to slider in MarkdownSplitEditor.
Once #3048 has merged, this PR will be merged.
- #3005 
- :radio_button: I have attached a screenshot/video to …
> apply theme color to slider in MarkdownSplitEditor

- browser/main/modals/NewNoteModal.styl
Fix: Chinese interface tab align.
**before:**
**after:**
- :black_circle: Bug fix (Change that fixed an issue)
- :black_circle: My code follows [the project code style](docs/code_style.md)
- :black_circle: All existing tests have been passed
- :black_circle: I have attached a screenshot/video to visualize my change if possible
> fix chinese language new note tab style

- browser/components/MarkdownSplitEditor.js
- browser/components/ModalEscButton.js
- browser/components/SideNavFilter.js
- browser/components/SnippetTab.js
- browser/lib/customMeta.js
- browser/main/Detail/FullscreenButton.js
- browser/main/Detail/InfoPanel.js
- browser/main/Detail/MarkdownNoteDetail.js
- browser/main/Detail/PermanentDeleteButton.js
- browser/main/Detail/SnippetNoteDetail.js
- browser/main/Detail/ToggleModeButton.js
- browser/main/Detail/TrashButton.js
- browser/main/NewNoteButton/index.js
- browser/main/NoteList/index.js
- browser/main/SideNav/PreferenceButton.js
- browser/main/SideNav/StorageItem.js
- browser/main/SideNav/index.js
- browser/main/modals/PreferencesModal/FolderItem.js
- browser/main/modals/PreferencesModal/FolderList.js
- browser/main/modals/PreferencesModal/index.js
- lib/main.development.html
- lib/main.production.html
Discard most of missing style warnings and other react warnings. It is also fixing broken style of preferences modal.
> Discard warnings

- browser/components/MarkdownPreview.js
- browser/lib/consts.js
- browser/main/lib/ConfigManager.js
- browser/main/modals/PreferencesModal/UiTab.js
Fix #3151
I've checked on production too.
MacOS
Windows
Ubuntu Linux
> Fix themes

- package.json
- yarn.lock
> Upgrade electron to v4

- docs/pt_BR/build.md
just to improve reading file
Minor changes to improve reading file
- :white_check_mark:  Documentation change (Change that modifies documentation. Maybe typo fixes)
- :white_check_mark: My code follows [the project code style](docs/code_style.md)
> minor changes

- browser/main/modals/PreferencesModal/InfoTab.js
updated Copyright (C) 2017 - 2019 BoostIO to Copyright (C) 2017 - 2020 BoostIO
> Copyright info updated

- contributing.md
Update the Korean translation section of `contribute.md`. Prior to this commit, the section seemed to refer to an older version of the file and had missing parts.
- Update existing translations to better match recent changes to the contribution guides
- Add new sentences to provide translations to newly added guides.
- :radio_button: My code follows [the project code …
> update Korean section of contributing.md

- docs/build.md
Update description of `Accessing code used in Pull Requests`.
No related issue
> Update build.md with correct description

- locales/fa.json
- locales/hu.json
- locales/ja.json
- locales/ko.json
- locales/pl.json
- locales/ru.json
- locales/th.json
- locales/tr.json
- locales/zh-CN.json
- locales/zh-TW.json
This pull request closes #3387. It adds language support for the "Ok" button in multiple languages.
> extended language support for multiple languages

- browser/lib/ui-themes.js
- browser/main/modals/PreferencesModal/ConfigTab.styl
- browser/styles/index.styl
This change adds a new very dark UI theme.
I've redone the PR #2880 with just the necessary changes to add the new theme (since the master include all the other changes).
- :radio_button: I …
> add Vulcan UI theme

- browser/main/SideNav/index.js
This is a fix for a bug that cause the preference button to stop working 
> Fixed wrong handler for setting button

- browser/components/MarkdownSplitEditor.js
Fixes #3512 
- :white_circle: This PR will modify the UI or affects the UX
- :white_circle: This PR …
> Fix scroll sync

- browser/main/lib/dataApi/attachmentManagement.js
- tests/dataApi/attachmentManagement.test.js
> Fix export path

- browser/main/modals/PreferencesModal/InfoTab.js
Update old Boostnote name to Boostnote legacy to clarify misunderstanding
> updated Boostnote name to Boostnote Legacy

- readme.md
This PR fix broken slack invite link
> updated slack invite link

- readme.md
> Community mobile version

- browser/components/MarkdownPreview.js
This change fixes the unclickable links.
- #3550
- :white_circle: This PR will modify the UI or affects …
> fix unclickable links

- browser/lib/markdown.js
- browser/main/lib/ConfigManager.js
- browser/main/lib/dataApi/formatHTML.js
This change avoids conflicting styles between inline codes and code blocks.
Here a short list of conflicting themes:
| Interface Theme | Preview Code Block Theme |
|:---------------:|:------------------------:|
|     Default     |     dracula, monokai     |
|      Dark       |         default          |
- #3554
- …
> avoid conflicting styles between inline codes and code blocks
